grafana/faro-web-sdk

jest.config.js, package.json, packages/core/jest.config.js, packages/web/jest.config.js, packages/web/package.json, packages/web/src/instrumentations/errors/registerOnerror.test.ts, packages/web/src/instrumentations/errors/registerOnerror.ts, yarn.lock
Make sure old onerror handler is preserved. Will see if I can add a test
=> Error instrumentation: preserve old onerror handler

dashboards/frontend-application.json, dashboards/grafana-agent-receiver.json
A basic dashboard to monitor the agent receiver.
Extra: updated measurement queries in frontend dashboard
=> Agent receiver dashboard

docs/sources/tutorials/quick-start-browser.md
This PR provides a copy edit of the Grafana Faro Web SDK get started docs.
=> docs: copy edits get started docs

demo/package.json
Fix running `docker compose up` after running `yarn clean`.
Fixes #88
=> Fix Docker compose after yarn clean

docs/sources/developer/releasing.md
Add some useful information for relasing Faro (thanks Bogdan :))
~- [ ] Tests added~
~- [ ] Changelog updated~
~- [ ] Documentation updated~
=> chore: add some additional hints for releasing

CHANGELOG.md
=> Prepare relase  v1.0.2

docs/sources/developer/releasing.md
* Add some additional info to reelase doc
=> chore: further refine release docs

packages/web-sdk/src/index.ts
This PR exports the SessionInstrumentation interface
Fixes #132
=> Exporting SessionInstrumentation interface (Issue#132)

packages/web-sdk/src/index.ts, packages/web-sdk/src/transports/batch/index.ts, packages/web-sdk/src/transports/batch/transport.ts, packages/web-sdk/src/transports/index.ts, packages/web-sdk/src/transports/otlp/index.ts, packages/web-sdk/src/transports/otlp/payload/OtelPayload.test.ts, packages/web-sdk/src/transports/otlp/payload/OtelPayload.ts, packages/web-sdk/src/transports/otlp/payload/index.ts, packages/web-sdk/src/transports/otlp/payload/transform/index.ts, packages/web-sdk/src/transports/otlp/payload/transform/toErrorLogRecord.test.ts, packages/web-sdk/src/transports/otlp/payload/transform/toEventLogRecord.test.ts, packages/web-sdk/src/transports/otlp/payload/transform/toLogLogRecord.test.ts, packages/web-sdk/src/transports/otlp/payload/transform/toMeasurementLogRecord.test.ts, packages/web-sdk/src/transports/otlp/payload/transform/toResourceLog.test.ts, packages/web-sdk/src/transports/otlp/payload/transform/toResourceSpan.test.ts, packages/web-sdk/src/transports/otlp/payload/transform/toScopeLog.test.ts, packages/web-sdk/src/transports/otlp/payload/transform/transform.ts, packages/web-sdk/src/transports/otlp/payload/transform/types.ts, packages/web-sdk/src/transports/otlp/payload/types.ts, packages/web-sdk/src/transports/otlp/transport.test.ts, packages/web-sdk/src/transports/otlp/types.ts
This is the thirds part Part of https://github.com/grafana/faro-web-sdk/pull/101.
It transforms the Faro Trace model to Otlpl compliant model.
Note:
The PR only shows that many files because I renamed a function which is used by them.
=> feat: add traces transform

CHANGELOG.md, packages/instrumentation-performance-timeline/package.json, packages/transport-batch/README.md, packages/transport-batch/package.json, packages/transport-otlp-http/README.md, packages/transport-otlp-http/package.json
=> chore: prepare release

experimental/CHANGELOG.md
Fix version  in experimental changelog
=> fix: version experimental changelog

SECURITY.md
Add a security.md file as suggested recently in security slack channel.
[Slack discussion](https://raintank-corp.slack.com/archives/CHQDPC970/p1683647856758019)
=> chore: add security.md file

demo/src/client/faro/initialize.ts
Remove PerformanceTimelineInstrumentation form demo.
=> chore: remove PerfTimelineInstrumentation from demo.

packages/web-sdk/src/instrumentations/errors/registerOnunhandledrejection.ts
=> fix: add stackFrames params to pushError in the unhandledrejection function

demo/src/client/faro/initialize.ts, docker-compose.yaml, packages/web-tracing/src/getDefaultOTELInstrumentations.ts
=> Fixing some parts of the demo

CHANGELOG.md, experimental/CHANGELOG.md
=> Updating changelog for 1.1.0

cypress/e2e/demo/events.cy.ts, demo/src/client/faro/initialize.ts
=> Lowering batching timeout? Fixing remote tests??

CHANGELOG.md
=> chore: prepare release v1.1.1

CHANGELOG.md
=> prepare realease 1.1.1

CHANGELOG.md, experimental/CHANGELOG.md
Update Changelogs to address release 1.2.3.
=> chore: prepare release 1.1.3

.github/PULL_REQUEST_TEMPLATE.md
Align with FE-O11Y Plugin template for easier handling
=> chore: align PR template with fe-o11y plugin template

CHANGELOG.md
I forgot to add a CHANGELOG entry for #249 
Add missing CHANGELOG entry
https://github.com/grafana/faro-web-sdk/pull/249
=> chore: add missing changelog entry for #249

CHANGELOG.md, experimental/CHANGELOG.md
Release 1.1.4
* Update CHANGELOGs
=> chore: prepare release 1.1.4

CHANGELOG.md
Prepare Minor release 
Enable new features
=> chore: prepare release 1.2.0

.github/dependabot.yaml
Chnage Dependabot interval to monthly
=> chore: change dependabot interval to monthly

CHANGELOG.md, experimental/CHANGELOG.md
fix:  release 1.2.0–1.2.2 fix version ranges in changelog
=> fix:  release 1.2.0–1.2.2 fix version ranges in changelog

CHANGELOG.md
=> chore: prepare release 1.2.4

CHANGELOG.md, packages/web-sdk/src/config/makeCoreConfig.ts
Release new, currently optional, tracked sessions management
=> chore: prepare release 1.2.5

demo/src/client/faro/initialize.ts
The demo should use new Faro features and reflect this in its setup.
* use new session manager with persistent sessions
=> chore: update demo config to use new Faro features

CHANGELOG.md
=> chore: prepare release 1.2.9

CHANGELOG.md
=> prepare release 1.3.3

CHANGELOG.md, experimental/CHANGELOG.md
=> chore: prepare release 1.3.5

experimental/transport-otlp-http/src/transport.test.ts
Forgot to dleet commente-out code.
cleanup
=> chore: remove commented out code

CHANGELOG.md, experimental/CHANGELOG.md
Unify changelog entries to align to the same pattern
=> Unify changelog entries to align to the same pattern

CHANGELOG.md
=> prepare release 1.3.5

packages/core/package.json, packages/core/src/transports/batchExecutor.ts, yarn.lock
testing out a suggestion from a kind contributor
=> removing murmurhash from core, using default map

CHANGELOG.md
=> chore prepare release 1.3.7

CHANGELOG.md
=> chore(release): prepare v1.4.2

CHANGELOG.md
prepare v1.5.0
Minor version upgrade because we introduced a new feature (React data support) which introduces a new/updated API
=> chore(release): prepare v1.5.0

README.md
We didn't had any description about hwo we release, our versioning scheme etc.
Add a section dicribing out release scheme
=> chore(docs): add releases section

CHANGELOG.md
=> Prepare release 1.5.1

packages/react/README.md
=> update faro react readme

packages/react/README.md
For the minimum React setup the ReactInstrumentation needs to be initiliazed and added to teh instrumentation error.
Update readme
=> chore: update minimum react setup

CHANGELOG.md, packages/web-tracing/src/types.ts
customer reported issue with build that was reported in this [slack thread](https://raintank-corp.slack.com/archives/C01T8C5CNTE/p1714773077383609)
=> fix: fixing import of Patterns in web tracing package

CHANGELOG.md
Hotfix release to fix a typing issue + a new option to define a custom log parser.
=> prepare release 1.7.1

CHANGELOG.md
Hotfix fo another type issue which was the result of updating react data router types.
=> prepare release 1.7.2

CHANGELOG.md
=> prepping 1.7.3 release

packages/react/README.md
Update import statements in router docs
=> chore(docs): add missing imports to router instrumentation docs

CHANGELOG.md, demo/src/client/faro/initialize.ts, experimental/CHANGELOG.md
Prepare Faro 1.8.0 release 
Update changelogs
=> chore(release): update changelog

demo/src/server/utils/verifyToken.ts
=> solve circular deps

CHANGELOG.md
=> chore(release): prepare 1.8.2

CHANGELOG.md
=> release 1.10.0

experimental/CHANGELOG.md
Update  version number in experimental log
=> update experimental log

CHANGELOG.md
Fixes a critical bug in the web-tracing xhr instrumentation
=> Prepare release 1.10.2

CHANGELOG.md
=> prepare release 1.11.0

.github/workflows/semantic-pr.yml
In order to enable more release automation
This Github actions definition will check the PR title against the conventional commit spec
https://www.conventionalcommits.org/en/v1.0.0/
=> chore: introduce PR checker for conventional PRs

CHANGELOG.md
=> chore(changelog): update

CHANGELOG.md
=> chore(release): prepare 1.12.2

.github/dependabot.yaml
Increase update intervall
* Increase update intervall
* Limit open PRs to 10
=> chore(dependabot): add config to for weekly security checks

.github/dependabot.yaml
=> chore: re-add scope for dependabot

.github/workflows/dependabot-automerge.yml
=> chore: fix depenabot fetch-metadata

.github/workflows/dependabot-automerge.yml
=> chore: fix interpolation

.github/workflows/dependabot-automerge.yml
=> chore: use squash and auto-approve when auto-merging

.github/dependabot.yaml
=> chore(dependabot): exlcude ua-parser v2.x updates

experimental/transport-otlp-http/package.json, packages/core/package.json, packages/web-tracing/package.json, yarn.lock
=> chore(deps): upgrade @opentelemetry/otlp-transformer to 0.57.1

demo/package.json
=> chore(deps): upgrade "@opentelemetry/sdk-node": "^0.57.1"

CHANGELOG.md
=> chore(release): prepare v1.13.0

CHANGELOG.md
=> chore(release): v1.13.1

CHANGELOG.md
=> chore(release): v1.13.2

demo/src/client/faro/initialize.ts
=> chore(demo): remove unused prop from faro instance

CHANGELOG.md
=> chore(release): prepare release 1.14

CHANGELOG.md
=> chore(release): prepare 1.14.1

CHANGELOG.md, experimental/CHANGELOG.md, experimental/transport-otlp-http/src/payload/transform/transform.ts, yarn.lock
=> chore(deps): upgrade otel deps

demo/tsconfig.json
=> chore(demo): update tsconfig to support multi module builds

.github/workflows/manage-milestones.yml
Uses correct trigger and job permissions.
=> fix: milestone management - assign permissions to job and trigger

CHANGELOG.md
=> chore(release): prepare 1.16

CHANGELOG.md
=> chore(release): prepare 1.17.2

.github/workflows/commands.yml, .github/workflows/manage-milestones.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, .github/workflows/semantic-pr.yml
Fix Zizmore findings in GH actions
**TODO**
Tackle all zizmor errors and warnings
=> fix(zizmor findings): tackle errors

CHANGELOG.md
=> chore(release): prepare v1.18.0

.github/zizmor.yml
enabling zizmor to run even on forks of the repo 
title
=> chore: adding zizmor config

CHANGELOG.md
=> chore(release): prepare 1.18.2

CHANGELOG.md
=> chore(changelog): update inconsistent entries

CHANGELOG.md
=> chore(release): 2.0.0 beta changelog

README.md
This PR adds the Faro v2 pre-release announcement to our README file to bring awareness and provide detailed information to upgrading guides.
=> chore(readme): add Faro v2 pre-release announcement to README

packages/web-tracing/src/index.ts
Fixes https://github.com/grafana/faro-web-sdk/issues/1576
=> fix(web-tracing): export FaroMetaAttributesSpanProcessor class

.github/workflows/release.yml
=> chore(ci): disable package manager cache
