grafana/faro-web-sdk

- demo/src/index.ts
- packages/core/src/transports/fetch.ts
Adds ability to provide request options when initializing fetch transport. Useful to configure any auth credentials required by receiver or any gateway in front of a receiver.
> Allow providing fetch options for fetch transport

- packages/meta-page/src/index.ts
Backend expcects `page.url` not `page.href`
> Page.href -> page.url

- package.json
- packages/core/README.md
- packages/core/jest.config.js
- packages/core/package.json
- packages/core/src/config/types.ts
- packages/core/src/transports/index.ts
- packages/core/src/transports/initialize.ts
- packages/core/src/transports/transports.test.ts
- packages/core/src/transports/types.ts
- yarn.lock
This PR adds ability to modify or filter events before they are sent over the wire.
Primary use case is to filter out "noise", expected errors that can't be easily prevented.
Config gets two new properties:
`ignoreErrors` - Array of strings or regexes. Errors with messages matching these will be dropped
`beforeSend` - Hook that accepts `TransportItem` and returns `TransportItem` or `null`. Can be used to write custom filter or transform the payload
> Feature: filter events before sending

- CHANGELOG.md
- demo/src/index.html
- docs/sources/tutorials/quick-start-browser.md
- packages/core/README.md
- packages/core/src/api/exceptions/index.ts
- packages/core/src/api/exceptions/initialize.test.ts
- packages/core/src/api/exceptions/initialize.ts
- packages/core/src/api/exceptions/types.ts
- packages/core/src/api/index.ts
- packages/core/src/api/initialize.ts
- packages/core/src/api/logs/index.ts
- packages/core/src/api/logs/initialize.ts
- packages/core/src/api/measurements/index.ts
- packages/core/src/api/measurements/initialize.ts
- packages/core/src/api/meta/initialize.ts
- packages/core/src/api/traces/index.ts
- packages/core/src/api/traces/initialize.ts
- packages/core/src/config/types.ts
- packages/core/src/index.ts
- packages/core/src/initialize.ts
- packages/core/src/transports/types.ts
- packages/core/src/utils/tests.ts
- packages/web/README.md
- packages/web/src/config.ts
- packages/web/src/instrumentations/errors/index.ts
- packages/web/src/instrumentations/errors/registerOnerror.ts
- packages/web/src/instrumentations/errors/registerOnunhandledrejection.ts
- packages/web/src/instrumentations/errors/stackFrames.ts
This pr adds a method to capture exceptions from `Error` objects:
```javascript
const err = new Error('bad thing happend');
grafanaAgent.api.pushError(err);
```
Notes:
Added `parseStacktrace` parameter to core config, so that web / node agents can supply own stacktrace parser
fixes #20
> Feature: agent.api.pushError method

- docs/sources/tutorials/quick-start-browser.md
This fixes a small typo in `docs/sources/tutorials/quick-start-browser.md`.
`doSoemthing()` -> `doSomething()`
> Docs: Fix typo doSoemthing -> doSomething

- CHANGELOG.md
- docs/sources/tutorials/quick-start-browser.md
- packages/core/README.md
- packages/core/src/agent.test.ts
- packages/core/src/config/types.ts
- packages/core/src/index.ts
- packages/core/src/initialize.ts
- packages/core/src/transports/initialize.ts
- packages/core/src/transports/types.ts
- packages/core/src/types.ts
- packages/core/src/utils/tests.ts
- packages/web/src/config.ts
Adds ability to pause the agent, preventing events from being sent to transports.
Can be used when you do not want to track certain pages in your SPA.
Alternative to https://github.com/grafana/grafana-javascript-agent/pull/29
> Add agent.pause() and agent.unpause()

- dashboards/frontend-application.json
First attempt at dashboard for frontend applications, in "export" format.
Contains web vitals, some stats and pivots for errors + browser stats and page views.
Notable ommission: sessions, we don't have meta for it yet.
> Dashboard for frontend application

- cypress/e2e/demo/events.cy.ts
- cypress/support/commands.ts
- cypress/support/e2e.ts
- dashboards/frontend-application.json
- dashboards/grafana-agent-receiver.json
- demo/src/actions.ts
- demo/src/index.html
- docs/sources/tutorials/quick-start-browser.md
- packages/core/README.md
- packages/core/src/api/events/index.ts
- packages/core/src/api/events/initialize.ts
- packages/core/src/api/events/types.ts
- packages/core/src/api/index.ts
- packages/core/src/api/initialize.ts
- packages/core/src/api/types.ts
- packages/core/src/config/types.ts
- packages/core/src/index.ts
- packages/core/src/transports/const.ts
- packages/core/src/transports/types.ts
- packages/web/src/config/makeCoreConfig.ts
- packages/web/src/consts.ts
- packages/web/src/index.ts
Adds `agent.api.pushEvent`, aligned as much as possible with [Events API OTEP](https://github.com/open-telemetry/oteps/blob/main/text/0202-events-and-logs-api.md). [Sister PR on the receiver side](https://github.com/grafana/agent/pull/2075).
Example:
```typescript
agent.api.pushEvent('navigation', { url: window.location.href });
```
Event domain defaults to `browser` for the web, to align with [otel semantics proposal](https://github.com/martinkuba/opentelemetry-specification/pull/1/files).
Open question: should we compile a set of semantic consts for common event names and attributes?..
fixes #48 
TODO:
> Events API

- CHANGELOG.md
- packages/web/src/transports/fetch/transport.test.ts
- packages/web/src/transports/fetch/transport.ts
- packages/web/src/transports/fetch/types.ts
This updates `FetchTransport` to drop events for a period after receiving 429 too many requests. The period is taken from `Retry-After` header if present, or 5 seconds default. This should help with spam. 
fixes #45
> Add backoff for fetch transport upon rate limiting

- .gitignore
The empty log file still allowed git to track changes. This removes it while keeping the directory.
> Remove empty log file to avoid tracking changes of it

- GOVERNANCE.md
- LICENSING.md
https://github.com/grafana/faro now exists and has the project base.
> Remove governance in favor of project base repository

- CHANGELOG.md
- README.md
- packages/core/src/transports/initialize.ts
- packages/core/src/transports/transports.test.ts
I wanted to add two instances of `FetchTransport` to my side project, one to sent to cloud endpoint, one to an agent instance.
It didn't work, as `transports.add` deduplicates transports by name, which is the same for all instances of `FetchTransport`.
I'm certain that adding multiple instances of `FetchTransport` is a legit use case, updated to dedupe by reference only. 
Also updated `transports.remove`. Previously it would remove the last instance with the same name, and would not remove it if it was first in the transport list -  `0` is `false` :)
> Allow multiple instances of same transport type

- README.md
**What is this feature and why do we need it?**
Seems like the link to @grafana/faro-react was broken. This PR should fix that.
> Fix broken link in readme 

- LICENSING.md
**What is this feature and why do we need it?**
Licensing.md was saying that default license is AGPL, but it's supposed to be Apache v2. Thanks @devnewton for spotting this
fixes #70
> Update Licensing.md to specify correct default license

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/CHANGE_REQUEST.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- .github/PULL_REQUEST_TEMPLATE.md
**What is this feature and why do we need it?**
This PR brings templates for Github issues. I also changed the PR template a little bit to stay in sync with the new ones.
**Which issue(s) does this PR fix?**:
**Checklist**:
> Add Github templates

- CHANGELOG.md
- packages/web-tracing/package.json
- packages/web-tracing/rollup.config.js
Remove the `"type": "module"` property from `package.json` in `web-tracing` package to avoid having bundling issues.
Fixes #82
> Remove type module from package.json

- packages/react/README.md
Hey 👋  I noticed a tiny typo when reading the guide.
> Fix typo "Farp" -> "Faro"

- CHANGELOG.md
- packages/core/src/metas/types.ts
With this PR we remove the `started` property from the `MetaSession` interface. 
This is because the `collector` does accept this property. 
It is also not used anywhere in the web-sdk so it is save to remove it.
#98 Remove started property from session meta
- ~[ ] Tests added~
> chore: remove `started` prop

- README.md
- docs/sources/developer/architecture/components/api.md
- docs/sources/developer/architecture/components/instrumentations.md
- docs/sources/developer/architecture/components/internal-logger.md
- docs/sources/developer/architecture/components/metas.md
- docs/sources/developer/architecture/components/transports.md
- docs/sources/developer/architecture/components/unpatched-console.md
- docs/sources/developer/architecture/initialization.md
- packages/core/README.md
This PR brings new internal docs for understanding the Faro internal architecture. This should help new joiners with understanding how Faro works.
Writing new transports and instrumentations docs will be provided in a separate PR.
> Update internal docs

- packages/web-sdk/src/instrumentations/webVitals/instrumentation.ts
The `get` prefix of the function names to receive WebVitals is deprecated and changed to `on`.
Fixes #
Change deprecated function names to the new naming scheme.
Old:
```js
import { getCLS, getFCP, getFID, getINP, getLCP, getTTFB } from 'web-vitals';
```
New:
```js
import { onCLS, onFCP, onFID, onINP, onLCP, onTTFB } from 'web-vitals';
```
Fixes #106 
~- [ ] Tests added~
~- [ ] Changelog updated~
~- [ ] Documentation updated~
> chore(WebVitalsInstrumentation): change deprecated functions names

- packages/web-sdk/src/instrumentations/session/instrumentation.ts
- packages/web-sdk/src/instrumentations/view/instrumentation.ts
The Session and View Instrumentation had a wrong sdk version attached.
This happened due to a wrong import of the VERSION constant.
Fixes issue #100
> Fix: wrong version for Session and View instrumentations

- docker-compose.yaml
- infra/tempo/config/tempo.yaml
* Align `tempo.yaml` to [new breaking changes coming with `Tempo v2.0.0`](https://github.com/grafana/tempo/releases)
* Pin Tempo version in `docker-compose.yaml` to avoid issues with future breaking changes
Fixes #119 
~- [ ] Tests added~
~- [ ] Changelog updated~
~- [ ] Documentation updated~
> 119 upgrade docker compose tempo config to use tempo 2x

- CHANGELOG.md
- packages/web-sdk/src/transports/fetch/transport.ts
Have fetch transport consume response body. If it's not consumed, request is not considered finished.
> have fetch transport read the response body

- docs/sources/tutorials/use-cdn-library.md
The versions in teh CDN tutorial still had the beta version numbers.
Use caret range with new V.1.0.* instead of the beta version tag.
> chore(cdn tutorial): use correct version numbers

- CHANGELOG.md
- packages/web-tracing/src/getDefaultOTELInstrumentations.ts
- packages/web-tracing/src/instrumentation.ts
- packages/web-tracing/src/types.ts
When using the Faro/Otel TraceInstrumentation people need to configure the (cors) URLs for which requests shall have trace headers added.
Currently this is not obvious from our docs and it's not possible to configure this directly via `TracingInstrumentation`.
Currently people need to re-add the standard Otel Instruments we are using in the TracingInstrumentationand and add the config there.
```ts
new TracingInstrumentation({
instrumentations: [
new DocumentLoadInstrumentation(),
new FetchInstrumentation({
ignoreUrls: ["the-collector-url"],
propagateTraceHeaderCorsUrls: [
new RegExp("https://foo.com/*")
]
}),
new XMLHttpRequestInstrumentation({
ignoreUrls: ["the-collector-url"],
propagateTraceHeaderCorsUrls: [
new RegExp("https://foo.com/*")
]
}),
new UserInteractionInstrumentation()
] …
```
> Add option to configure URLs which should include trace header

- CHANGELOG.md
- docs/sources/tutorials/quick-start-browser.md
In the `quickl-start-browser` tutorial for adding Faro with OpenTelemetry support, we instantiated `new FaroTraceExporter({ faro })`.
This does not work because  the`FaroTraceExporter` receives `api` as the only constructor parameter and we forgit to add the destructuring assignment like this `new FaroTraceExporter({ ...faro })`.
Fixes #
Slightly related to: #160
A user had some problems because he referred to this example.
> chore(docs): Add missing destructuring assignment

- demo/package.json
Demo app crashes when user has an ad-blocker activated.
In the video you see first how the menu expands when clicking the hamburger menu.
Next, after activating the ad-blocker, the menu doesn't expand anymore.
Browser console shows a Vite server error:`http://localhost:5173/node_modules/.vite/deps/web-vitals.js?v=9a30861b`
The Vite server could not download an asset which was blocked by an ad-blocker.
This is a weird behavior of the Vite dev server an there is no fix for that as disabling the ad-blocker.
See [Vite Docs - "Browser extensions"](https://vitejs.dev/guide/troubleshooting.html#browser-extensions)
Solution:
Start the Vite in prod mode (node-env set to production). 
Changes:
* Use prod strict on start: `"start": "yarn serve:prod",`
* Add dev script for easy starting the dev …
> Demo app crashes when user has an ad-blocker activated

- CHANGELOG.md
- docs/sources/developer/releasing.md
- experimental/CHANGELOG.md
- lerna.json
Chnage version scheme back to the "single version for all packages approach"
Tested indepednent versionoing with the addition of experimental packages. 
Which only leads to maintenance overhead, greater source for compatibility problems and confusion for customers about which versions will work together.
> chore: align version scheme to have the same version for all packages.

- experimental/instrumentation-performance-timeline/README.md
Update docs to reflect that all config props for a PerformanceEntry can be used with Faro too. 
Fixes #176
> chore: explain how to add additional config options

- experimental/instrumentation-performance-timeline/src/instrumentation.test.ts
- experimental/instrumentation-performance-timeline/src/instrumentation.ts
Add check if PerformaceObserver is supported. 
In case a browser does not have support, stop initialization of the instrument.
> chore: add support check for performance observer

- docker-compose.yaml
The path has changed upstream to /bin/grafana-agent
Fixes running the demo application and other uses of the docker-compose environment
> docker-compose: fix grafana-agent path

- GOVERNANCE.md
Adds Governance.md to faro-web-sdk
https://github.com/grafana/faro/issues/3
These aren't needed:
- [ no ] Tests added
- [ no ] Changelog updated
- [ no ] Documentation updated
> Moving GOVERNANCE.md from faro to faro-web-sdk

- CHANGELOG.md
- experimental/transport-otlp-http/src/payload/transform/toErrorLogRecord.test.ts
- experimental/transport-otlp-http/src/payload/transform/transform.ts
- packages/core/README.md
- packages/core/src/api/exceptions/initialize.test.ts
- packages/core/src/api/exceptions/initialize.ts
- packages/core/src/api/exceptions/types.ts
Add option to put extra context to exception logs.
I kept the API similar to Logs API where we add additional context via the options object.
[Cloud docs PR to show how to add additional error context](https://github.com/grafana/cloud-docs/pull/922).
Fixes #
Fixes #141
> add additional error context to excceptions API

- CHANGELOG.md
- packages/core/src/globalObject/globalObject.ts
This PR changes the `GlobalObject` to be computed from `globalThis`, `global` and `self`, rather than sticking to `global` if `window` is not defined. 
Background: I am currently building a browser extension, which uses webworkers to run background tasks. Those webworkers don't have a `global` nor a `window` object. The current implementation in core fails and leads to errors. By using `globalThis` the issue can be mitigated, as `globalThis` is present in Node, where it points to `global`, in a usual browser window, where it points to `window` and in webworkers, where it points to `self` (I think).
I just went with this check I implemented because that is also what was used in Typescript:
https://github.com/microsoft/TypeScript/blob/v4.6.4/src/compiler/corePublic.ts#L119-L122
> Core: Use `globalThis` rather than `window`

- experimental/CHANGELOG.md
- experimental/transport-otlp-http/src/payload/transform/toErrorLogRecord.test.ts
- experimental/transport-otlp-http/src/payload/transform/toEventLogRecord.test.ts
- experimental/transport-otlp-http/src/payload/transform/toLogLogRecord.test.ts
- experimental/transport-otlp-http/src/payload/transform/toMeasurementLogRecord.test.ts
- experimental/transport-otlp-http/src/payload/transform/transform.ts
- experimental/transport-otlp-http/src/transport.test.ts
- Assign `payload.trace?.span_id` instead of `spanId: payload.trace?.trace_id` 
- Add `context` to LogLogRecord attributes  array
> fix: add correct span_id and add context to log

- experimental/CHANGELOG.md
- experimental/instrumentation-performance-timeline/src/instrumentation.test.ts
- experimental/instrumentation-performance-timeline/src/instrumentation.ts
Remove entry types which are not supported by the browser so that we only observe supported entry types.
> chore: only observe supported entry types

- CHANGELOG.md
- experimental/transport-otlp-http/src/transport.ts
- packages/core/README.md
- packages/core/src/testUtils/mockTransport.ts
- packages/core/src/transports/base.ts
- packages/core/src/transports/initialize.ts
- packages/core/src/transports/transports.test.ts
- packages/core/src/transports/types.ts
- packages/web-sdk/src/transports/fetch/transport.ts
This pull request ensures that the implementations of the Transport interface that were accepting a single item in their `send` function, will work as expected. This type of Transports is getting deprecated instead and will be removed with v2
> Make single TransportItem transports backwards compatible

- CHANGELOG.md
- packages/core/README.md
- packages/core/src/transports/base.ts
- packages/core/src/transports/initialize.ts
After some suggestions by @bfmatei, there might be cases of transports that require instantaneous execution of the signal (such as a WebSocket, a Console or any stream). To that end, this commit removes the deprecation notice of the un-batched transports and instead changes the core logic which is responsible for sending the item.
> Clean up batch processing

- .browserslistrc
- experimental/instrumentation-fetch/.browserslistrc
- experimental/instrumentation-fetch/package.json
- experimental/instrumentation-performance-timeline/.browserslistrc
- experimental/instrumentation-performance-timeline/package.json
- experimental/transport-otlp-http/.browserslistrc
- experimental/transport-otlp-http/package.json
- package.json
- packages/core/.browserslistrc
- packages/core/package.json
- packages/react/.browserslistrc
- packages/react/package.json
- packages/web-sdk/.browserslistrc
- packages/web-sdk/package.json
- packages/web-tracing/.browserslistrc
- packages/web-tracing/package.json
In order to indicate to downstream consumers the compile targets to allow polyfilling, this change adds the browserslist entries to each package.json of the provided packages in the repo.
> Add browserslist to faro packages

- CHANGELOG.md
- packages/web-tracing/package.json
- packages/web-tracing/src/getDefaultOTELInstrumentations.ts
- yarn.lock
This instrumentation is very chatty and should only be enabled when needed. It is not needed for the default set of instrumentations.
Fixes #
> Remove OTel user-interaction instrumentation from the default set

- CHANGELOG.md
- demo/package.json
- packages/web-tracing/package.json
- yarn.lock
Update was delayed till the sequelize maintainers tackledit because it was only used in the Demo app, not in production. It's also not part of the Web-SDK itself.
I manually tested the Demo environment to see if everything is working. 
* Had the console open to watch for console.logs or network errors
* Inspected some payloads
* Used the test functions in the demo to create events, traces, errors and so on
Could not find any problems so far.
Fixes #
* [dottie vulnerable to Prototype Pollution (CVE-2023-26132)](https://github.com/grafana/faro-web-sdk/security/dependabot/34)  
* [Connection confusion in gRPC (CVE-2023-32731)](https://github.com/grafana/faro-web-sdk/security/dependabot/37)
> Update deps affected by a CVE

- demo/package.json
- packages/web-tracing/package.json
- yarn.lock
We released a new Faro version because of a critical CVE where we first thought the web-tracing package is affected.
But I discovered that only the demo is affected. Web-Tracing doesn't have a dependency to exporter-trace-otlp-grpc.
This PR removes the dependency from the web-tracing package and adds it to the demo package
> chore: move forced grpc resolution to demo package

- docs/sources/developer/releasing.md
For a Faro release we always update the version of all package, even if the packages had no changes.
To ensure Lerna is updating all package version add `--force-publish` to teh update call.
> chore: update release docs

- docs/sources/tutorials/quick-start-browser.md
UserInteractionInstrumentation is not part of the faro default instrumentation anymore.
> fix: removing UserInteractionInstrumentation from quickstart

- experimental/CHANGELOG.md
- experimental/instrumentation-fetch/README.md
- experimental/instrumentation-fetch/src/constants.ts
- experimental/instrumentation-performance-timeline/README.md
- experimental/instrumentation-performance-timeline/src/instrumentation.test.ts
- experimental/instrumentation-performance-timeline/src/instrumentation.ts
To prevent naming collisions with user defined RUM events to the best extend possible, let's namespace internal Faro events. 
For example `performanceEntry` will become `faro.performanceEntry`.
> 236 prefix event names which are specific to faro to prevent naming collisions

- packages/web-tracing/package.json
- yarn.lock
The package `opentelementry/instrumentation` which we use in the `Web-Tracing` package has the package 
`import-in-the-middle` as a dependency.
import-in-the-middle has a vulnerability rated with a base score of 9.8 - CRITICAL. To fix it  we updated the the related OTel package as well as all the other OTel packages uses by the instrumentation.
Using the Faro demo I additionally did a manual check if traces data is sent correctly 👍 
Fixes #
* [CVE-2023-38704](https://nvd.nist.gov/vuln/detail/CVE-2023-38704)
* [[security] - import-in-the-middle Support for Faro #7051 ](https://github.com/grafana/support-escalations/issues/7051)
> fix: CVE-2023-38704

- demo/vite.config.ts
- experimental/CHANGELOG.md
- experimental/transport-otlp-http/src/payload/OtelPayload.ts
- experimental/transport-otlp-http/src/payload/index.ts
- experimental/transport-otlp-http/src/payload/transform/index.ts
- experimental/transport-otlp-http/src/payload/transform/transform.ts
- experimental/transport-otlp-http/src/payload/transform/types.ts
- experimental/transport-otlp-http/src/payload/types.ts
- experimental/transport-otlp-http/src/transport.test.ts
- experimental/transport-otlp-http/src/transport.ts
The `faro-transport-otlp-http` used the wrong OTLP structure when sending the respective signals
The problem happened in the `OtlpHttpTransport.class` when iterating over the `OtelTransportPayload` object.
The `OtelTransportPayload` object has the following structure:
```ts
export interface OtelTransportPayload {
readonly resourceLogs: Readonly<ResourceLogs>;
readonly resourceSpans: Readonly<ResourceSpans>;
}
```
In the `sendPayload` method in `OtlpHttpTransport` we iterate over the object and do some signal specific configuration before sending the signal.
The respective loop looks like this:
```ts
for (const [key, value] of Object.entries(payload)) { ... }
```
When stringifying the signal payload to attach it to the requests body we did:
```ts  
const body = JSON.stringify(value); // …
```
> 252 oltphttptransport resulting in 400 response status

- CHANGELOG.md
- experimental/CHANGELOG.md
- experimental/transport-otlp-http/src/payload/transform/transform.ts
- packages/core/README.md
- packages/core/src/api/exceptions/initialize.ts
- packages/core/src/api/measurements/initialize.test.ts
- packages/core/src/api/measurements/initialize.ts
- packages/core/src/api/measurements/types.ts
The measurement API lags support of adding contextual attributes.
Note:
This requires changes or udates to the following components as well:
* Grafana Agent
* Faro Receiver
* Docs (Website)
❗️Important❗️
Do not merge/release this PR until the Agent and Receivers changes have been merged and released.
Introduce an optional `context` object to pass with the `PushMeasurementOptions` object. Similar to the Logs and Errors APIs. 
* [PR Receiver (merged)](https://github.com/grafana/app-o11y-kwl-endpoint/pull/262) 
* [PR Agent](https://github.com/grafana/agent/pull/4975)
* [PR Docs](https://github.com/grafana/website/pull/15059)
> 254 make it possible to provide extra attributes to the measurements meta

- docker-compose.yaml
In a former PR the binary name of the Grafana Agent got changed back to the old version.
With [Grafana Agent version 31](https://grafana.com/docs/agent/v0.31/upgrade-guide/#v0310) the agent binary was renamed from `agent` to `grafana-agent`
Add the correct binary name to docker-compose file
> fix: add correct binary name for grafana agent

- .drone/drone.yml
Drone.yaml used node version `lts-stretch` which pointed to the old node lts which is not supported anymore
- In drone.yaml change node version from `node:lts-stretch` to `node:lts-bookworm`
> chore: update node version to current release (>= 18)

- experimental/instrumentation-fetch/src/instrumentation.test.ts
- experimental/instrumentation-fetch/src/instrumentation.ts
- package.json
- packages/web-sdk/src/config/makeCoreConfig.test.ts
- yarn.lock
the reference types/node package in the project is not important and updates cause some trouble, so I removed it
This also fixes some test issues:
> deps: remove types node

- .nvmrc
- Dockerfile
We recently updated the Node version to the current LTS release (lts/hydrogen, v18) but did not update the node version used in the Dockerfile which still used Node 16.
Strangely the built didn't fail when testing it.
* Update Dockerfile to use Node 18 (node:18-alpine)
* Be more explicit about node lts version in nvmrc.
[Issue](https://github.com/grafana/faro-web-sdk/issues/350)
> fix: move node version in Dockerfile to current lts (v18)

- CHANGELOG.md
- experimental/CHANGELOG.md
- packages/web-sdk/src/config/makeCoreConfig.ts
prepare release 1.2.1
* Update CHANGELOGs
* Add note that new session management is in PoC state and not meant for production use
> chore: prepare release 1.2.1

- CHANGELOG.md
- packages/web-sdk/src/transports/fetch/transport.test.ts
- packages/web-sdk/src/transports/fetch/transport.ts
Fetch limits payloads to 64 kibibytes when using the keepalive option by throwing a network error.
Turn off keepalive when payload length is over 60_000. This allows the request to succeed with the caveat that it can still be canceled by the browser during page unload. This is a balanced compromise until a better solution is found.
Fixes #192
Standard
https://fetch.spec.whatwg.org/#http-network-or-cache-fetch
> fix(web-sdk): disable keepalive when large payload

- CHANGELOG.md
- packages/web-sdk/src/config/makeCoreConfig.test.ts
- packages/web-sdk/src/metas/k6/meta.ts
needed in order for the collector to properly unmarshal the k6 meta object
> adding isK6Browser to k6 meta payload

- CHANGELOG.md
- docs/sources/developer/architecture/components/metas.md
- packages/core/src/metas/registerInitial.ts
- packages/web-sdk/src/index.ts
- packages/web-sdk/src/metas/index.ts
- packages/web-sdk/src/metas/sdk/index.ts
- packages/web-sdk/src/metas/sdk/meta.ts
The information conveyed by the SDK meta has no relevance for RUM. 
Since the meta is sent with each beacon requests —and contains long strings—it unnecessarily adds to each requests payload size.
We reduced the default content of the sdkMeta to only contain the version number of the library. 
This can be done in that way because we always update all Faro packages to the same version number.
* Remove the sdk meta from the default metas.
* Provide sdkMeta as a separate export so users can add it via the init function.
**Example:**
```ts
import { sdkMeta } from '@grafana/faro-web-sdk';
initializeFaro({
url: ...,
...
metas: [sdkMeta],
});
```
[GH Issue](https://github.com/grafana/faro-web-sdk/issues/305)
[Related discussion](https://github.com/grafana/faro-web-sdk/discussions/271)
> change: remove sdk meta from default metas

- CHANGELOG.md
- packages/core/src/metas/registerInitial.ts
- packages/web-sdk/src/instrumentations/session/instrumentation.test.ts
Session attributes provided on initialize were not added to the meta.
This happened due to the implementation of the (future) new session manager.
What happened was that the `createSessionMeta` called internally by the new session manager created a new session object. 
The meta initializer checked if this new object exists and if so, uses the new session meta instead of the current one provided by the user.
Session Attributes are not being sent #371
> fix: don't overwrite customer session attributes

- CHANGELOG.md
- packages/core/src/config/types.ts
- packages/core/src/metas/registerInitial.ts
- packages/web-sdk/src/config/makeCoreConfig.test.ts
- packages/web-sdk/src/config/makeCoreConfig.ts
- packages/web-sdk/src/instrumentations/session/instrumentation.test.ts
- packages/web-sdk/src/instrumentations/session/instrumentation.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/PersistentSessionsManager.test.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/VolatileSessionsManager.test.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.test.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.ts
- packages/web-sdk/src/transports/fetch/transport.test.ts
- packages/web-sdk/src/transports/fetch/transport.ts
We want to release the new session management capabilities so users can already use it if they like.
The current (legacy) session object will be removed from the Faro config as of 2024/01/01. 
It also fixes an issue that session from session storage were not picked up on initialize.
* Rename the new session config object
* Remove legacy session object if new session management is enabled
* Fix: createSessionMeta() didn't pick up session from session storage (only from local storage)
[Documentation PR](https://github.com/grafana/website/pull/16343)
> feat: preview of new session manager

- CHANGELOG.md
- experimental/instrumentation-fetch/README.md
- experimental/instrumentation-fetch/src/constants.ts
- experimental/instrumentation-fetch/src/instrumentation.test.ts
- experimental/instrumentation-fetch/src/instrumentation.ts
- experimental/instrumentation-xhr/README.md
- experimental/instrumentation-xhr/src/instrumentation.test.ts
- experimental/instrumentation-xhr/src/instrumentation.ts
- experimental/instrumentation-xhr/src/types.ts
In order to propagate a client-side session id to the server side without needing a trace necessarily.
Propagate an `x-faro-session` header to the server containing the session ID.
> Add x-faro-session header to identify client session to server

- CHANGELOG.md
- packages/web-sdk/src/transports/fetch/transport.test.ts
- packages/web-sdk/src/transports/fetch/transport.ts
Adding the x-faro-session header for legacy sessions caused a problem with memcached which starts to stack up so we remove this for now. 
This change does affect an internal feature so no degredation of features for customers.
* Don't add x-faro-session-id to beaon requests for  legcacy sessions.
> hotfix: remove custom sessionId  header from legacy session.

- CHANGELOG.md
- packages/web-sdk/src/transports/fetch/transport.test.ts
- packages/web-sdk/src/transports/fetch/transport.ts
Because of a backend issue—which got fixed—we needed to disable to always add the new x-faro-session-id header.
* Always add x-faro-session-id header
> change: always add x-faro-session-id HTTP header

- CHANGELOG.md
- packages/core/src/config/types.ts
- packages/web-sdk/src/instrumentations/session/index.ts
- packages/web-sdk/src/instrumentations/session/instrumentation.test.ts
- packages/web-sdk/src/instrumentations/session/instrumentation.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/PersistentSessionsManager.test.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/PersistentSessionsManager.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/VolatileSessionManager.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/VolatileSessionsManager.test.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/index.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sampling.test.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sampling.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionConstants.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.test.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/types.ts
- packages/web-sdk/src/utils/index.ts
With this PR we introduce a first version of session based sampling.
We use a head based sampling strategy based on sessions.
This means, if a session is not part of the sample we drop all events related to this session.
We calculate a sampling decision on the following points in time:
- On initialize, if either no session is persisted in web-storage or if the persisted session is invalid
- When we extend a session
- When the setSession() method is called outside of Faros' default session logic (if users "manually" call the function)
Settings:
- Users can either config a sample rate or use a sampler function to define a sample based on a custom calculation
-  Faro inject a `context` parameter which current;y only contains the metas. 
- The function returns a number
- If sampleRate or the …
> Session based sampling V0

- CHANGELOG.md
- demo/README.md
- packages/core/src/api/meta/initialize.ts
- packages/core/src/semantic.ts
- packages/react/src/router/v4v5/activeEvent.ts
- packages/react/src/router/v6/FaroRoutes.tsx
- packages/react/src/router/v6/types.ts
- packages/web-sdk/src/index.ts
- packages/web-sdk/src/instrumentations/view/instrumentation.ts
To be able to properly visualize view and page transitions we need information about the previous route or view. 
We provide this information with the attributes object of the respective event. 
**Breaking change**
The event for route transitions got renamed from `routeChange` to `route_change`.
This is to be compliant with the structure of the other semantic events in Faro which are in the forma `{namespace}_{action}`
* Rename the `routeChange` event to `route_change` to be compliant with the Faro event naming scheme.
* Add `{from|to}Route` and `{from|to}Url` attributes to the route transition event (`route_change`).
* De-noise route transition events by only sending a route transition to a different route then the current one.
* Update demo README to the new event name of the route …
> feat: capture view and route transitions

- CHANGELOG.md
- packages/react/package.json
Fixes the following warning when running `yarn install` in this repository
```warning "workspace-aggregator-08102a81-82fa-4a72-b370-86363f217eff > @grafana/faro-react > react-router-dom@6.16.0" has unmet peer dependency "react-dom@>=16.8".```
Added a missing peer dep (and added it as a dev dep)
N/A
> fix: add missing `react-dom` peer dependency

- CHANGELOG.md
- demo/package.json
- demo/src/server/otel/initialize.ts
- docs/sources/tutorials/quick-start-browser.md
- packages/core/package.json
- packages/web-tracing/package.json
- packages/web-tracing/src/faroTraceExporter.ts
- packages/web-tracing/src/instrumentation.ts
- packages/web-tracing/src/sessionSpanProcessor.ts
- packages/web-tracing/src/types.ts
- yarn.lock
`@opentelemetry/api-metrics` is unused, and it is also deprecated: https://www.npmjs.com/package/@opentelemetry/api-metrics
I removed the unused `@opentelemetry/api-metrics` dependency declaration.
In addition, I noticed that `@opentelemetry/sdk-trace-base` is used - this is not necessary. `sdk-trace-web` and `sdk-trace-node` both re-export the entirety of the `base` package, so there's no need for an explicit dependency.
N/A
> fix: remove unused OTel `api-metrics` dependency

- CHANGELOG.md
- packages/web-sdk/src/instrumentations/session/instrumentation.test.ts
- packages/web-sdk/src/instrumentations/session/instrumentation.ts
Storing the initial session in local storage always set teh samplng decsion to true which causes that we always send 100% of the signals.
Faro attributes are always strings, so the following 
evaluation always evaluates to `true`.
```ts
isSampled: Boolean(initialSessionMeta.attributes!['isSampled']),
```
Chaged the evaluation so we evaluate if string attribute has value 'true' or not
> fix: initial sampling decision was set tu true

- CHANGELOG.md
- demo/src/client/faro/initialize.ts
- packages/core/src/config/types.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.test.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.ts
Add an option to provide a custom id generator function. 
This is for custoners who use their own session naming scheme.
* Add optional `sessionIdGenerator` property to the session tracking object
* enhance `createUserSessionObject()` function to use the `sessionIdGenerator`. I sessionIdGenerator is not provided Faro uses the internal shortId genearot function.
[Documentation](https://github.com/grafana/website/pull/16964)
> Custom-session-id-generator

- CHANGELOG.md
- packages/core/src/config/types.ts
- packages/web-sdk/src/instrumentations/session/instrumentation.test.ts
- packages/web-sdk/src/instrumentations/session/instrumentation.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.test.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.ts
User defined session attributes were missing in the session meta.
The current flow is:
* User defined attributes—either added during the init phase  or later via setSession()—are added to the meta we sent to the backend
* The are also stored with the FaroUserSession in local storage.
* Session attributes will be picked up from local storage when resuming sessions, also across page loads
* Fix bug were initial session attributes were not send
* Store session attributes in web-storage to make them outlive page loads
https://github.com/grafana/faro-web-sdk/assets/47627413/93102918-244b-45d0-ba7b-559a259f042d
I forgot to show in the video that attributes are also picked up om session_resume
> User defined attributes are missing in the session meta

- CHANGELOG.md
- packages/web-sdk/src/instrumentations/session/instrumentation.ts
I'm not sure why, but we sometimes get an error from Faro with `cannot read property 'toString' of undefined`. It doesn't happen with all users, only some
Makes sure there's a valid value on which to call `toString`
> fix: guard against missing `isSampled` attribute

- CHANGELOG.md
- packages/web-sdk/src/instrumentations/session/sessionManager/PersistentSessionsManager.ts
The PersistetSessionManager registered a listener to the storage event and updated the session if a storage event was emitted from another browsing context.
This syncronisarions could lead to a case were multiple session_extend events are send.
The synchronisation is superflous and should be removed.
Remove session sync on storage event
https://github.com/grafana/faro-web-sdk/assets/47627413/4bfcbbaf-5884-481d-a8c5-2aa5ab8705b3
https://github.com/grafana/faro-web-sdk/assets/47627413/f231c73e-fa55-4aea-96c1-c0b2a0d53fed
> fix: remove storage sync between browser contexts.

- CHANGELOG.md
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionConstants.ts
to better align to common naming schemes as well as grafana naming for local web-strorage keys
Change key to use reverese domain notation as pefix. `'com.grafana.faro.session'`
> chore: use reverse domain name as web-storage item prefix

- experimental/CHANGELOG.md
- experimental/transport-otlp-http/src/transport.test.ts
- experimental/transport-otlp-http/src/transport.ts
Browsers put size restrictions on the body size of requests sent with the beacon API.
This can lead to data loss for large payloads.
* Disable `keepalive` if body size exceeds 60kb
> feat: disable `keepalive` if body size is >= 60 kb

- CHANGELOG.md
- packages/core/src/utils/is.ts
The check for `undefined` by using a function will fail on React Native, as `Event` will be needed to be accessed to pass it as an argument, and it's not defined.
Such check will fail in the browser as well:
Use the "classic" check instead
> fix: fix the check for presence of Event

- packages/web-sdk/src/transports/fetch/transport.ts
It can happen that the transpiled JS code of the FetchTransport to get the sessionId from the sessionMeta will cause an error if the session meta is absent. 
Since the exception is handled, Faro will not send the respective item.
It caused by translating a property retrieval where we use optional chaining.
Instead of optional chaining use explicit code to check if session meta is available.
> FetchTransport: make sessionId retrieval more stable

- demo/src/client/faro/initialize.ts
- experimental/transport-otlp-http/README.md
- experimental/transport-otlp-http/src/payload/OtelPayload.test.ts
- experimental/transport-otlp-http/src/payload/OtelPayload.ts
- experimental/transport-otlp-http/src/payload/transform/index.ts
- experimental/transport-otlp-http/src/payload/transform/toErrorLogRecord.test.ts
- experimental/transport-otlp-http/src/payload/transform/toMeasurementLogRecord.test.ts
- experimental/transport-otlp-http/src/payload/transform/transform.ts
- experimental/transport-otlp-http/src/payload/transform/types.ts
- experimental/transport-otlp-http/src/transport.ts
- experimental/transport-otlp-http/src/types.ts
Enhancement request from the community
> Faro web vitals measurements are sent without a body field in the OTLP transport. The body field is optional in the [Otel Log spec](https://opentelemetry.io/docs/specs/otel/logs/data-model/#field-body) but can cause issues with Otel Collector components (e.g. Splunk HEC Exporter).
* Keep the current behavior but provide options to the user to configure a custom string which will be attached as a body property.
* Provide this functionality also to logs of type `Exception`
* Do a small refactoring to reduce the number of parameter in `OtelPayload.ts`
* Update docs
Resolves: #430
> 430 add body field for measurement logs for otlp transport

- docker-compose.yaml
Running the DEMO on Mac hardware like an Mx will fail without support for ARM. `v1.14.1` looks to be the first to support `arm64`. 
```
✔ Container faro-web-sdk-cortex-1                                                                                                                       Recreated0.1s 
! cortex The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s 
⠋ Container faro-web-sdk-agent-1                                                                                                                        Creating0.0s 
```
Bumped the version of `cortex` to one that supports ARM.
[Cortext Dockerhub](https://hub.docker.com/r/cortexproject/cortex/tags)
> fix: patch demo for arm64

- CHANGELOG.md
- packages/web-tracing/src/instrumentation.ts
Traces generated only contain `service.name` and `service.version` based on the MetaApp data.
https://github.com/grafana/faro-web-sdk/blob/a5f43a1f1bbe1f5a0c02546fe32c9d651f6a20db/packages/core/src/metas/types.ts#L28
MetaApp also has `environment`, but that is not propagated to the traces.
OpenTelemetry has the `deployment.environment` attribute as standard attribute for environment which can be filled.
It is possible to fill the attribute through initialisation, see 
https://ceesbos.nl/posts/20240108-grafana-faro-trace-with-deployment-environment/
But better is to make it part of the library itself and fill the standard attributes.
> Add deployment.environment filled with MetaApp environment variable

- infra/cortex/config/cortex.yaml
I just cloned a fresh repo to my WSL ubuntu distro and was not able to run the `cortex` container
See:
Cortex config according to official docs: https://cortexmetrics.io/docs/configuration/configuration-file/
> fix: cortex config for demo

- CHANGELOG.md
- packages/web-sdk/src/instrumentations/performance/performanceUtils.test.ts
- packages/web-sdk/src/instrumentations/performance/performanceUtils.ts
- packages/web-sdk/src/instrumentations/performance/types.ts
Response time was missing in resource timing.
Response time is part of the fetch time, but we need it for more granular insights.
Add response time to Faro resource entries.
> chore: add missing response time

- CHANGELOG.md
- packages/web-tracing/package.json
- yarn.lock
user reported issue (#457) regarding a dependency breaking builds
bumping dependency to latest version
[thread in dependency repo describing issue](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1892)
> chore: bump @opentelemetry/instrumentation-document-load dependency to ^0.35.0

- CHANGELOG.md
QpL release.
Updates Otel dependencies in web-tracing package
Update changelog
> prepare release 1.3.8

- CHANGELOG.md
- packages/web-sdk/src/instrumentations/performance/navigation.ts
- packages/web-sdk/src/instrumentations/performance/performanceUtils.test.ts
- packages/web-sdk/src/instrumentations/performance/performanceUtils.ts
- packages/web-sdk/src/instrumentations/performance/types.ts
Duration of a resource load was missing
* Add resource load `duration` property
* Rename `totalNavigationTime` property to duration
* Make calculation of `faro.performance.navigation` entries explicit.
- `calculateFaroNavigationTiming()` now calls `calculateFaroResourceTiming()`. Before both methods were called separately, e. g. by the `navigation` instrumentation, to calculate a nav timing.
- The `navigation` instrumentation now needs only to call `calculateFaroNavigationTiming()` to calculate a `faro.performance.navigation` entry.
> Add resource load duration

- CHANGELOG.md
- packages/web-sdk/src/metas/browser/meta.ts
We have gotten several Sentry reports about a crash `Cannot read properties of undefined (reading 'brands')` from this file. Apparently some browsers does have the field `userAgentData` defined, but its value is undefined.
Adds an extra check that `userAgentData` is truthy before trying to read it.
> fix: crash when navigator.userAgentData is undefined

- CHANGELOG.md
Patch release which fixes an issue happening because  `navigator.userAgentData` is initialized with `undefined` value in some browsers.
It also adds the missing `duration` prop to `faro.performance.resource` events (currently in preview).
> prepare patch release 1.3.9

- CHANGELOG.md
- packages/web-sdk/src/config/getWebInstrumentations.ts
- packages/web-sdk/src/config/types.ts
Enable performance timeline instrumentation to deliver value for performance insights early.
* Enable instrumentation by default
* Write docs: 
-  issue: #481 
Docs PR (privaet repo): https://github.com/grafana/faro/issues/11
> feat: enable performance timeline by default

- CHANGELOG.md
- demo/src/client/faro/initialize.ts
- packages/web-tracing/jest.config.js
- packages/web-tracing/package.json
- packages/web-tracing/src/faroTraceExporter.ts
- packages/web-tracing/src/faroTraceExporter.utils.test.ts
- packages/web-tracing/src/faroTraceExporter.utils.ts
- packages/web-tracing/src/index.ts
- packages/web-tracing/src/instrumentation.ts
- packages/web-tracing/src/sampler.test.ts
- packages/web-tracing/src/sampler.ts
**1. Sampling**
Faro has a probabilistic sampler, but when tracing is enabled, the sampling decision is not promoted to the OpenTelemetry-JS tracer which lead to problems if backend traces are sampled as well. 
> The implication is that when the SDK has chosen not to sample, the Otel tracer will still propagate the desire to sample downstream, creating undesired side-effects for `parentbased_always_off` scenarios.
**2. Sending a Faro event for client spans** 
Open tasks:
* Add sampler which reads the `isSampled` flag from the session meta and sets the otel sampling decision based on that flag.
* Send a Faro event for spans of `kind=client`
> 480 create opentelemetry trace sampler taking faro sampling decisions into account

- CHANGELOG.md
- packages/web-sdk/src/instrumentations/session/instrumentation.test.ts
- packages/web-sdk/src/instrumentations/session/instrumentation.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.ts
The started timestamp of a Faro session was reset for valid, resumed sessions on page-load.
This will lead to start time drifting between client an backend which eventually leads to rejected sessions because the session reached the lifetime limit.
* Keep original start time for resumed valid sessions so backend and client timestamps are always in sync. 
Fixes issue: #512
> 512 session manager started timestamp is reset on page load aka session resume

- CHANGELOG.md
- packages/core/src/api/events/initialize.test.ts
- packages/core/src/api/events/initialize.ts
- packages/core/src/api/events/types.ts
- packages/core/src/api/exceptions/initialize.test.ts
- packages/core/src/api/exceptions/initialize.ts
- packages/core/src/api/exceptions/types.ts
- packages/core/src/api/logs/initialize.test.ts
- packages/core/src/api/logs/initialize.ts
- packages/core/src/api/logs/types.ts
- packages/core/src/api/measurements/initialize.test.ts
- packages/core/src/api/measurements/initialize.ts
- packages/core/src/api/measurements/types.ts
- packages/web-tracing/src/faroTraceExporter.utils.test.ts
- packages/web-tracing/src/faroTraceExporter.utils.ts
The new `faro.trace.*` events which are sent  per child span have always the same  traceId and spanId. 
TraceID of course is correct when they belong to the same trace, but the spanId is different.
When attaching `TraceContext` (`spanId` and `traceId`) to a signal, Faro pulls the active span from the otel context and receives the IDs from this span. 
This is not always correct. 
Say we want to send a signal for a specific span:
With the old behavior each call to a Faro api, e. g. `pushEvent` will auto receive `traceId` and `spanId` from the active span, which is wrong.
Provide an option to inject `spanContext` for the specific span when calling an Faro api. 
The API will  pick up the `spanContext` and uses that values instead of the active span.
* Update each Faro api except `pushTraces` …
> Add span context when sending faro events which belong to specific spans

- CHANGELOG.md
- demo/src/client/faro/initialize.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.ts
If DOM storage is diabled teh web-sdk got stuck in a loop.
This is because in the `updateSession` we fetch a session from DOM storage, validate it and then either update the last activity timestamp of the valid session or create a new session.
In case DOM storage is not available, we always get a `null` value for stored session which is invalid.
So we only update the in-memory session meta with the new session.
Creating a new session via this function is basically a session extend, so it causes a session extend event to be send, which in turn leads to that the update function is called again, which cuases teh inifnifte loop beacuse the above steps are executed over and over again. 
*Responsible part of the update function*
```ts
if (isUserSessionValid(sessionFromStorage)) { …
```
> fix: infinite loop if session dom storage is turned off

- CHANGELOG.md
- demo/src/client/faro/initialize.ts
- packages/react/README.md
- packages/react/src/index.ts
- packages/react/src/router/index.ts
- packages/react/src/router/initialize.ts
- packages/react/src/router/types.ts
- packages/react/src/router/v6/FaroRoutes.tsx
- packages/react/src/router/v6/index.ts
- packages/react/src/router/v6/initialize.ts
- packages/react/src/router/v6/routerDependencies.ts
- packages/react/src/router/v6/types.ts
- packages/react/src/router/v6/withFaroRouterInstrumentation.ts
- packages/react/src/types.ts
This PR adds support for the React Router V6 which is using the new [RouterProvider](https://reactrouter.com/en/main/routers/router-provider) which supporting the new Data Routers.
[Setting up Routes with `RouterProvider` works differently then before](https://reactrouter.com/en/main/upgrading/v6-data#migrating-to-routerprovider).
On result of this is that we can't wrap the React Routes with `FaroRoutes` anymore. 
Also wrapping the `RouterProvider` with `FaroRoutes` also doesn't work because `FaroRoutes` are using `useLocation` internally which is not available outside of the Data Routers.
To instrument the new routers we created the `withFaroRouterInstrumentation(router)` which subscribe to route changes of the passed router and sends the respective Faro route change events. …
> 235 faroroutes support for routerprovider react router v6

- packages/react/README.md
Upgrade Faro React docs to reflect new capabilities for data routers.
* Include how to instrument Data Routers
* Include upgrade guide from V6 to V6 Data Routers
> chore(docs): Update Faro-React docs, add upgrade instructions

- docs/sources/developer/architecture/components/metas.md
- packages/core/src/metas/types.ts
- packages/web-sdk/src/config/makeCoreConfig.test.ts
- packages/web-sdk/src/metas/k6/meta.ts
Starting from k6 v0.50.0 the `window.k6` object will contain the `testRunId` field populated with the test run ID.
The test run ID can be used to reference the test run in Grafana Cloud, as well as to distinguish tests executed in the K6 browser farm from local ones.
The ETA for k6 v0.50.0 release is March 25th
Update the k6 meta to include `testRunId` if available
[Docs PR website, cloud docs](https://github.com/grafana/website/pull/18955)
> feat(k6): add  testRunId to k6 meta if available in k6 object

- CHANGELOG.md
- packages/web-sdk/src/instrumentations/session/instrumentation.test.ts
- packages/web-sdk/src/instrumentations/session/instrumentation.ts
Structured clone. caused issues in sandboxes which wrap some things in proxy objects.
JSON.stringify omits invalid objects or sets them to null.
Did no own benchmarks but scimming a bit trhrough teh web it seems that we don't gain any performance benefits when using `structuredClone`.
Last but not list this simplifies the code and we get reid of  statement as well.
*  Remove `structuredClone` and use the JSON method to deep copy objects.
* [Slack 1](https://raintank-corp.slack.com/archives/C04LHN01GN7/p1710930121069309)
* [Slack 2](https://raintank-corp.slack.com/archives/C03E2AQKU2W/p1710498855153949)
* [MDN JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description)
> chore(sessions): remove structured clone

- CHANGELOG.md
- packages/web-sdk/src/instrumentations/performance/navigation.test.ts
- packages/web-sdk/src/instrumentations/performance/navigation.ts
- packages/web-sdk/src/instrumentations/performance/performanceUtils.test.ts
- packages/web-sdk/src/instrumentations/performance/performanceUtils.ts
- packages/web-sdk/src/instrumentations/performance/resource.test.ts
- packages/web-sdk/src/instrumentations/performance/resource.ts
- packages/web-sdk/src/instrumentations/performance/types.ts
When comparing page-load time with time spent in the browser, let's say dom and render timings + response time, there is notable delta between the sum of the latter timings and page-load time.
After some investigation, the results are:
Faro is working correct and we derive all timings as they should be, but why the delta?
We did some manual math and it turns out that the delta is _mostly_ related to the time the browser needs to parse the document.
So the plan is calculate parser time as well.
Unfortunately the current performance timeline doesn't provide and event to retrospectively get the timestamp when the parser is starting it's work. In the image below you can see that we have `responseEnd` followed by `domInteractive`.
One could argue  that we simply can use `domInteractive - …
> Add missing parsing time

- CHANGELOG.md
- packages/web-sdk/README.md
- packages/web-tracing/README.md
The README files in the web-sdk and web-tracing packages still had the pre-release warning.
* Remove pre-release warning from web-sdk and web-tracing package
> docs: remove pre-release note from web-sdk and web-tracing readme

- CHANGELOG.md
* Update the performance instrumentation which reduces resource entries tracked by default. 
* Remove redundant DocumentLoadInstrumentation instrumentation from web-tracing package
> chore(release): prepare v1.5.2

- CHANGELOG.md
- packages/react/src/router/v6/types.ts
- packages/react/src/router/v6/withFaroRouterInstrumentation.ts
There was type issue with newest react (data) router.
Add specific types for `Index` and `NonIndex` routes.
We took the necessary properties from the `RouteObject` type as defined by the remix/react router.  
Update types in `withFaroRouterInstrumentation` to satisfy the React Router `RouteObject` type.
> Update types to work with v6 data routers

- demo/package.json
- packages/react/README.md
- packages/react/src/router/v6/types.ts
- yarn.lock
Type issue with react router v6.23.0 and `dependencies.createRoutesFromChildrens`
Note: 
Got some help from the community. @riboher helped with reporting and testing 🙏 
See: https://github.com/grafana/faro-web-sdk/issues/582
Update `ReactRouterV6CreateRoutesFromChildren` type to include `RouteObjectV6DataRouter`
> Faro react type issues create routes from children

- .nvmrc
nvmrc had a diferent node lts version then teh one used by the CI.
Use current lts version lts/iron
> use current node lts version in nvmrc

- CHANGELOG.md
- docs/sources/developer/architecture/components/metas.md
- experimental/CHANGELOG.md
- experimental/transport-otlp-http/src/payload/transform/toResourceLog.test.ts
- experimental/transport-otlp-http/src/payload/transform/toResourceSpan.test.ts
- experimental/transport-otlp-http/src/payload/transform/transform.ts
- packages/core/src/metas/types.ts
- packages/web-sdk/src/metas/browser/meta.ts
Track layout viewport dimension.
This can e. g. provide insights about different behavior in different viewports, enables to filter signals by viewport size and more.
* add two new properties to the browser meta: `viewportWidth` and `viewportHeight`
> Track window dimensions

- CHANGELOG.md
- packages/web-sdk/src/instrumentations/session/instrumentation.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionConstants.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.test.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/types.ts
- packages/web-sdk/src/transports/fetch/transport.test.ts
- packages/web-sdk/src/transports/fetch/transport.ts
We noticed an edge case where stored session timings drift and the collector rejects session even if Faro automatically extend the session.
The receiver was updated to deal with this.
Anyways to be on the save side we will handle the response in Faro and create a new Session if needed.
The Faro receiver now returns a 202 with the custom header `X-Faro-Session-Status` with value `invalid` if a session is invalid.
The header is not attached for 202 response of a valid session.
* [Faro receiver PR](https://github.com/grafana/app-o11y-kwl-endpoint/pull/438)
> 590 grafana cloud create new session if 400 session invalid is returned

- CHANGELOG.md
- packages/core/src/api/index.ts
- packages/core/src/api/logs/const.ts
- packages/core/src/api/logs/index.ts
- packages/core/src/api/logs/initialize.ts
- packages/core/src/index.ts
- packages/web-sdk/src/config/makeCoreConfig.test.ts
- packages/web-sdk/src/config/makeCoreConfig.ts
https://github.com/grafana/faro-web-sdk/pull/580 introduced the `logArgsSerializer` option in the core. But it isn't usable through `initializeFaro` from the web-sdk since the `makeCoreConfig` doesn't forward the option.
I tried to follow the patterns of the surrounding code, which is why I introduced the new `defaultLogArgsSerializer` to use as a fallback. If `logArgsSerializer` is not set on the browser config this default is used.
I didn't find any documentation that could be updated alongside with this change. If there is a place I should document this, please let me know.
> feat(web-sdk): forward logArgsSerializer in initializeFaro to the core

- CHANGELOG.md
- packages/react/package.json
`react-router-dom` is an optional dependency, and should be marked as such.
`react-dom` only exists since `react-router-dom` has its own peer dep on it.
Use `peerDependenciesMeta` (works in all package managers)
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta
> fix: mark peer deps `react-dom` and `react-router-dom` as optional

- .prettierignore
- CHANGELOG.md
- demo/index.html
- demo/src/server/middlewares/index.ts
- demo/src/server/middlewares/serverTiming.ts
- demo/src/server/routes/registerRoutes.ts
- packages/core/src/api/events/index.ts
- packages/core/src/api/index.ts
- packages/core/src/index.ts
- packages/web-sdk/src/instrumentations/performance/navigation.test.ts
- packages/web-sdk/src/instrumentations/performance/navigation.ts
- packages/web-sdk/src/instrumentations/performance/performanceUtils.test.ts
- packages/web-sdk/src/instrumentations/performance/performanceUtils.ts
- packages/web-sdk/src/instrumentations/performance/performanceUtilsTestData.ts
- packages/web-sdk/src/instrumentations/performance/resource.test.ts
- packages/web-sdk/src/instrumentations/performance/resource.ts
Create correlation between faro events for navigations by attaching a server-sent identifier
Extract server-timing contents and use it to add span context.
Enhance demo to send trace parent via server-timing.
Fixes: #452
> feat: collect tracecontext through server-timing for nav and resource timings

- CHANGELOG.md
Fix a problem where span status wasn't corretly set in web-tracing fetch
> Set span status on erroneus fetch requests (#641)

- CHANGELOG.md
- cypress/e2e/demo/errors.cy.ts
- demo/src/client/faro/initialize.ts
- demo/src/client/pages/Features/ErrorInstrumentation.tsx
- demo/src/client/pages/Features/TracingInstrumentation.tsx
- packages/web-tracing/src/instrumentation.ts
- packages/web-tracing/src/instrumentationUtils.test.ts
- packages/web-tracing/src/instrumentationUtils.ts
The underlying instrumentation does not always set the correct span error status for erroneous XHR requests.
This PR ensures that the span error status is reliably set.
* Use `applyCustomAttributesOnSpan` for `XMLHttpRequestInstrumentation` to set the span status
* Update the Faro demo to trigger XHR requests for success and error. 
* For demo purposes add a custom `applyCustomAttributesOnSpan` for xhr and fetch requests which prints a console.log.
https://github.com/grafana/faro-web-sdk/assets/47627413/9f033a59-4af4-43d5-98d6-6b1ac0780d70
> Set correct span error state for xmhlhttprequest

- CHANGELOG.md
- demo/src/client/faro/initialize.ts
- packages/core/src/api/events/initialize.test.ts
- packages/core/src/api/events/initialize.ts
- packages/core/src/api/events/types.ts
- packages/core/src/api/exceptions/initialize.test.ts
- packages/core/src/api/exceptions/initialize.ts
- packages/core/src/api/exceptions/types.ts
- packages/core/src/api/logs/initialize.test.ts
- packages/core/src/api/logs/initialize.ts
- packages/core/src/api/logs/types.ts
- packages/core/src/api/measurements/initialize.test.ts
- packages/core/src/api/measurements/initialize.ts
- packages/core/src/api/measurements/types.ts
- packages/core/src/utils/date.ts
- packages/core/src/utils/getCurrentTimestamp.ts
- packages/core/src/utils/index.ts
- packages/web-sdk/src/instrumentations/performance/navigation.test.ts
- packages/web-sdk/src/instrumentations/performance/navigation.ts
- packages/web-sdk/src/instrumentations/performance/resource.test.ts
- packages/web-sdk/src/instrumentations/performance/resource.ts
The timestamp of a signal sent via the Faro API represents the exact moment when the respective API was called.
This precision is sufficient for most cases but for some it's not.
**Example:**
Faro's performance instrumentation collects the relevant data after the document's readyState changes to 'complete' [1]. When the performance item is sent via the Faro API, the timestamp reflects the moment the Faro signal is created, not the actual time when the event occurred. The option to provide a timestamp adjustment resolves this discrepancy.
To solve above issue we:
* Provide an option to to pass a timestamp overwrite to all Faro APIs (except pushTrace API)
* Calculate the actual timestamp of when a resource or navigation event occurred and pass this value as the correction timestamp
We …
> 652 navigation timing is off set

- CHANGELOG.md
- packages/web-tracing/src/getDefaultInstrumentations.test.ts
- packages/web-tracing/src/getDefaultOTELInstrumentations.ts
- packages/web-tracing/src/instrumentation.ts
- packages/web-tracing/src/types.ts
The opentelemetry.js fetch and xhr instrumentation add some extra network event by default.
For a lot of users it is not useful and creates unnecessary additional payload as well.
Faro's already tracks resource events so the data is redundant.
Note: 
currently the resource instrumentation doesn't map the resource to its respective trace id
* Disable network events by default
* Refactor option creation and move it into `getDefaultWebInstrumentations()` because it doesn't belong to the instrumentation class
* Allow users to enable network events via the `TracingInstrumentation()` class.
* [Docs PR](https://github.com/grafana/website/pull/21098)
* [List of network events](https://github.com/open-telemetry/opentelemetry-js/blob/d4035eb9733c101d53780033a4e58caebec73619/packages/opentelemetry-sd …
> chore(web-tracing): ignore network events by default

- CHANGELOG.md
Minor version upgrade because web-tracing now doen't add network events by default.
> prepare release 1.9.0

- docs/sources/tutorials/use-angular.md
`getWebInstrumentations` was not imported and is needed
Import `getWebInstrumentations`
- [n/a] Tests added
- [n/a] Changelog updated
> Update use-angular.md, Add etWebInstrumentations import

- CHANGELOG.md
- experimental/CHANGELOG.md
- experimental/transport-otlp-http/src/transport.test.ts
- experimental/transport-otlp-http/src/transport.ts
The otlp-http-transport didn't consume the response body which can cause issue like memory leaks, hanging requests, sever not releasing resources etc.
* Consume response body
> chore(otlp-http-transport): consume response body

- README.md
We don't have dedicated OSS Faro docs yet.
Since there's currently no difference between the Faro docs for OSS and cloud we link them in the README.
* Link cloud docs in README file
> chore(docs): link cloud docs in README

- packages/core/src/api/exceptions/index.ts
- packages/core/src/api/exceptions/initialize.test.ts
- packages/core/src/api/exceptions/initialize.ts
- packages/core/src/api/exceptions/types.ts
JS allows to add a cause to errors. 
For example when re-throwing an error with a more specific  error message but to still have access to the original error.
Currently users need to do this manually by adding the cause to the extended error context.
Since this is a standard prop of the Error object Faro should take care of extarcting and adding it. 
* Extract `error.cause`  and attach it to the extended Faro error context
> chore(pushError): automatically add error.cause to the extended error context

- .markdownlint.json
- CHANGELOG.md
- experimental/CHANGELOG.md
- experimental/transport-otlp-http/src/payload/transform/toResourceLog.test.ts
- experimental/transport-otlp-http/src/payload/transform/toResourceSpan.test.ts
- experimental/transport-otlp-http/src/payload/transform/transform.ts
**otlp-http-transport**
* Resource attribute `service.namespace` was missing.
* Some browser attributes were aligned to the current OTEL spec (still in experimental)
- `browser.user_agent` is replaced by `user_agent.original`
- `browser.os` is replaced by `browser.platform`
See above
* [Spec: resource attributes browser](https://opentelemetry.io/docs/specs/semconv/resource/browser/)
> chore(otlp-http-transport): update semantic attributes

- packages/react/README.md
The import for createBrowserRouter in the Faro react readme pointed to faro-react instead of 'react-router-dom'
* Update import statement
* [PR cloud docs (private)](https://github.com/grafana/website/pull/22086)
* [PR  frontend-o11y app (private)](https://github.com/grafana/app-o11y-kwl/pull/1157)
> fix(readme): import for createBrowserRouter no pints to react-router-dom

- CHANGELOG.md
- cypress/e2e/demo/logs.cy.ts
- packages/web-sdk/src/instrumentations/console/instrumentation.test.ts
- packages/web-sdk/src/instrumentations/console/instrumentation.ts
The console instrumentation sends a log message for each console log level. 
For `console.error()` logs this behavior oftentimes lead to confusion because users expect it to be send as an error and available in the dedicated errors overviews in Grafana cloud.
Faro now sends a error log in case of a console.error message.
* Send an error log if log level is `error`
> Console instrumentation: send a Faro error for console.error logs

- CHANGELOG.md
- packages/web-sdk/src/instrumentations/session/sessionManager/PersistentSessionsManager.test.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/PersistentSessionsManager.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/VolatileSessionManager.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/VolatileSessionsManager.test.ts
- packages/web-sdk/src/utils/json.test.ts
- packages/web-sdk/src/utils/json.ts
We had reports that Fare throws a "Maximum call stack size exceeded"  exception when strigifying a users session object before storing in in web-storage.
This usually happens when an object contains circular references.
To prevent the error we provide an object sanitizer which removes circular dependencies from object with a `null` value.
Since the respective object needs to be discovered before, we do not loose data.
* Provide utility function to remove circular references from objects 
* Use this function in  `storeUserSession` in `VolatileSessionManager` and `PersistendSessionManager` 
* [Issue](https://github.com/grafana/faro-web-sdk/issues/587#issuecomment-2436545283)
> improvement(storeUserSession) guard object stringifier against circular references

- GOVERNANCE.md
Make links mentioned in the [GOVERNANCE.md](https://github.com/grafana/faro-web-sdk/blob/main/GOVERNANCE.md) up-to-date
Changed the project name from faro to faro-web-sdk in paths
> chore: Fix links in the GOVERNANCE.md

- CHANGELOG.md
- cypress/e2e/demo/errors.cy.ts
- cypress/e2e/demo/logs.cy.ts
- packages/web-sdk/src/instrumentations/console/instrumentation.test.ts
- packages/web-sdk/src/instrumentations/console/instrumentation.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/PersistentSessionsManager.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/VolatileSessionManager.ts
- packages/web-sdk/src/utils/index.ts
- packages/web-sdk/src/utils/json.test.ts
- packages/web-sdk/src/utils/json.ts
The console instrumentation for console.error logs stringifies objects provided from outside faro.
Those object can contain circular references which will cause `JSON.stringify()` to fail
* Provide a new convenience function to stringify external objects 
* Use that function where appropriate
* Prefix errors send for console.error with `console.error: `
> fix(console instrumentation): handle circular object references in json parser for console.error

- CHANGELOG.md
- packages/core/src/config/types.ts
- packages/web-sdk/src/config/makeCoreConfig.ts
- packages/web-sdk/src/instrumentations/console/instrumentation.test.ts
- packages/web-sdk/src/instrumentations/console/instrumentation.ts
- packages/web-sdk/src/instrumentations/console/types.ts
Some users want to send log signals instead of errors for console.error messages. 
* add config option to choose to send logs instead of errors
* Move ConsoleInstrumentation config to Faro config and deprecate the old config.
- Note: we do support both for now
* Update the Faro documentation to reflect the changes
- [Docs PR (internal)](https://github.com/grafana/website/pull/22766)
> refactor(ConsoleInstrumentation): Provide config option to send log messages for console.error calls

- .prettierignore
- demo/package.json
- lerna.json
- package.json
- yarn.lock
Update some Faro dev and demo properties to close some old dependabot security alerts.
Updated the folloeing packages:
* cookie-parser
* express
* cypress 
* lerna
[Executed `lerna repair` as recommended in the Lerna changelog](https://github.com/lerna/lerna/blob/main/CHANGELOG.md#breaking-changes)
> After updating we strongly recommend running lerna repair in your project. This will migrate your lerna.json to the latest and greatest and remove any outdated options.
* [Dependabot security alerts](https://github.com/grafana/faro-web-sdk/security/dependabot)
> chore(deps): update to latest version

- package.json
The last open dependabot security alert depedns on cypress. 
We alreay updated cypress to the latest version, but it still pulls the vulnerable tough-cookie version.
For now we pin the version to the non-vulnerable one.
* For now we pin the version via Yarn resolutions
> chore(deps-dev): pin tough cookie version

- CHANGELOG.md
- packages/web-sdk/src/instrumentations/console/instrumentation.ts
When sending standard log message for console logs we don't need an args mapper. 
Additionally the args mapper used there wasn't protected agains circular object references.
* Revert args mapper form pushLog for standard logs
> fix(ConsoleInstrumentation): guard json stringifier for non-error logs agains circular references

- packages/web-sdk/src/instrumentations/console/instrumentation.test.ts
- packages/web-sdk/src/instrumentations/console/instrumentation.ts
We revert to the default log parser behaviour and do not stringify object by default.
Faro provides an option to inject a custom log parser which customers can leverage if custom parsing logic is needed.
* use `defaultLogArgsSerializer` for errors
* use the former `this.api.pushLog(args, { level });` function which internally parses logs and applies the custom log parser if configured.
> fix(console instrumentation): revert to former log parsing behavior

- package.json
- yarn.lock
chore(deps): upgrade grafana/eslint-config to fix security alert
* https://github.com/grafana/faro-web-sdk/security/dependabot/81
> chore(deps): upgrade grafana/eslint-config to fix security alert

- .github/workflows/dependabot-automerge.yml
Small updates are frequent and tedious
Automatically merge patch updates through dependabot.
The main issue with this is that no downstream actions are triggered. If we need that, we need a personal access token to trigger the merge.
> chore: auto-merge patch updates

- CHANGELOG.md
- experimental/CHANGELOG.md
- experimental/transport-otlp-http/src/transport.test.ts
- experimental/transport-otlp-http/src/transport.ts
Don't send a requests if the respective traces or logs endpoint  URL is not set.
See above
> fix(transport-otlp-http): don't send payload if endpoint URL is empty

- packages/web-tracing/src/faroTraceExporter.utils.test.ts
- packages/web-tracing/src/faroTraceExporter.utils.ts
We need to indicate clearer how long some things tool
Add the duration in ns to the events. Why nanos not ms? Because OTel uses nanos.
> feat: add duration to events from traces

- demo/package.json
- yarn.lock
dependabot is having some issues, need to manually patch
> chore(deps): upgrade path-to-regexp from 0.1.10 to 0.1.12

- CHANGELOG.md
- Feat (`@grafana/faro-web-tracing`): add duration to events from traces (#861)
- Fix (`@grafana/faro-transport-otlp-http [experimental]`): Prevent sending requests when the
endpoint URL is not configured (#827).
A bunch of dependency updates which are closing CSVEs as well.
> chore(release): prepare 1.12.3

- demo/src/client/faro/initialize.ts
- experimental/transport-otlp-http/src/transport.test.ts
- packages/core/src/api/meta/initialize.ts
- packages/core/src/api/meta/initilialize.test.ts
- packages/core/src/api/meta/types.ts
- packages/core/src/index.ts
- packages/core/src/metas/index.ts
- packages/core/src/metas/types.ts
- packages/core/src/utils/index.ts
- packages/core/src/utils/is.test.ts
- packages/core/src/utils/is.ts
- packages/web-sdk/src/instrumentations/console/instrumentation.test.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/PersistentSessionsManager.test.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/PersistentSessionsManager.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/VolatileSessionManager.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/VolatileSessionsManager.test.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.test.ts
- packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.ts
- packages/web-sdk/src/utils/webStorage.test.ts
- packages/web-sdk/src/utils/webStorage.ts
As a user of Frontend O11y and Application O11y in Grafana Cloud, i would like to override the service name
for a subset of telemetry as the user progresses through the UX.
Example:
User lands on the login page, the telemetry should be mapped to the login service
User progresses through the app, goes to checkout, the associated telemetry should be associated with the checkout service
User manages their newsletter preferences, associated telemetry should be tagged with the profile service name
The override should be persisted in the user session to allow maximum flexibility.
TODO:
Faro provides two APIs to dynamically set overrides.
Under the hood it's nothing else as adding an overrides object to the session meta.
The receiver (for Grafana it's cloud only atm) reads the contents of the …
> feat: provide dynamic service name overrides

- docker-compose.yaml
Because the Postgres verison wasn't fixed in the docker-compoise file a DB update was pulled which broke the demo.
* Use fixed POstgres version instead of `:main`
> chore(demo): pin postgres version in docker compose

- .github/workflows/pull-request.yml
- CHANGELOG.md
- demo/package.json
- experimental/CHANGELOG.md
- experimental/instrumentation-fetch/package.json
- experimental/instrumentation-performance-timeline/package.json
- experimental/instrumentation-xhr/package.json
- experimental/transport-otlp-http/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
- packages/web-sdk/package.json
- packages/web-tracing/package.json
- yarn.lock
Define supported Node engines.
* Define Node engines in package.json engines object
* Update Github action to  build/test against Node 18 as well. 
* Update Github action to  build/test against Node version ranges instead of a fixed version number
* Downgrade rimraf to V5 because starting [with V6 rimraf needs Node version >= 20](https://www.npmjs.com/package/rimraf). 
- [This rimraf version has no known CVEs](https://security.snyk.io/package/npm/rimraf/5.0.10)
- [Node EOL table](https://endoflife.date/nodejs)
> chore: define supported Node engines 

- experimental/instrumentation-fetch/src/instrumentation.test.ts
- experimental/instrumentation-fetch/src/instrumentation.ts
- experimental/instrumentation-xhr/src/instrumentation.test.ts
- experimental/instrumentation-xhr/src/instrumentation.ts
- packages/web-sdk/src/instrumentations/errors/registerOnerror.test.ts
- packages/web-sdk/src/instrumentations/errors/registerOnerror.ts
- packages/web-sdk/src/instrumentations/errors/registerOnunhandledrejection.ts
- packages/web-sdk/src/metas/browser/meta.ts
Faro uses the window object in many places which can lead to issues if used in environments which don't provide a window object.
Faro's globalObject covers this and should be used instead of window.
Replace usage of window.* with  globalObject.*
> chore: use Faro globalObject  instead of window object

- experimental/instrumentation-fetch/src/instrumentation.test.ts
- experimental/instrumentation-fetch/src/instrumentation.ts
- experimental/instrumentation-xhr/src/instrumentation.test.ts
- experimental/instrumentation-xhr/src/instrumentation.ts
- packages/web-sdk/src/instrumentations/errors/registerOnerror.test.ts
- packages/web-sdk/src/instrumentations/errors/registerOnerror.ts
- packages/web-sdk/src/instrumentations/errors/registerOnunhandledrejection.ts
- packages/web-sdk/src/metas/browser/meta.ts
Revert the [former change](https://github.com/grafana/faro-web-sdk/pull/914/files) to use Faro's globalObject
> chore(globalWindow): revert using Faro's globalObject

- CHANGELOG.md
- packages/core/src/config/types.ts
- packages/web-sdk/src/index.ts
- packages/web-sdk/src/instrumentations/console/instrumentation.test.ts
- packages/web-sdk/src/instrumentations/console/instrumentation.ts
Reverts grafana/faro-web-sdk#902
reverting this PR in favor of #904 - that PR accomplishes what this PR intended to do and is more in line with the correct functionality
> chore: revert add custom error serializer to console instrumentation

- CHANGELOG.md
- Dockerfile
When running `docker compose --profile demo up -d` the following error was encountered:
```
[!] Error: Could not find specified tsconfig.json at /usr/app/experimental/instrumentation-xhr/tsconfig.bundle.json
at getTsConfigPath (/usr/app/node_modules/@rollup/plugin-typescript/dist/cjs/index.js:270:19)
at parseTypescriptConfig (/usr/app/node_modules/@rollup/plugin-typescript/dist/cjs/index.js:344:26)
at typescript (/usr/app/node_modules/@rollup/plugin-typescript/dist/cjs/index.js:800:27)
at exports.getRollupConfigBase (/usr/app/rollup.config.base.js:86:7)
at Object.<anonymous> (/usr/app/experimental/instrumentation-xhr/rollup.config.js:3:18)
at Module._compile (node:internal/modules/cjs/loader:1469:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
at …
```
> fix: demo build during installation

- CHANGELOG.md
- packages/core/src/api/exceptions/initialize.test.ts
- packages/core/src/api/exceptions/initialize.ts
- packages/core/src/index.ts
- packages/core/src/utils/index.ts
- packages/core/src/utils/json.test.ts
- packages/core/src/utils/json.ts
The optional context object users can add to an error can only be a flat object containing values of type string.
In this case the receiver rejects the requests with a status 400
Especially when using the Faro cdn version there's no type checking and a build in place so users wouldn't be aware in advance if a value is possibly not of type string.
**Note:**
For now we keep a fixed stringifier. If we get proof that users need to be able to inject a custom stringifier we add that functionality  
* Auto stringify all context values
> fix: add error context attributes stringifier

- CHANGELOG.md
- packages/core/src/api/events/initialize.test.ts
- packages/core/src/api/events/initialize.ts
- packages/core/src/api/logs/initialize.test.ts
- packages/core/src/api/logs/initialize.ts
- packages/core/src/api/measurements/initialize.test.ts
- packages/core/src/api/measurements/initialize.ts
- packages/core/src/utils/json.test.ts
Add a property stringifier for `attributes` and `context` to all Faro APIs
> chore: transform all properties in `context` and `attributes` objects to string

- demo/src/client/faro/initialize.ts
- packages/core/src/api/meta/initialize.ts
- packages/core/src/api/meta/initilialize.test.ts
- packages/core/src/api/meta/types.ts
- packages/core/src/config/types.ts
- packages/core/src/metas/types.ts
- packages/web-sdk/src/config/makeCoreConfig.test.ts
- packages/web-sdk/src/config/makeCoreConfig.ts
- packages/web-sdk/src/instrumentations/session/instrumentation.test.ts
- packages/web-sdk/src/instrumentations/session/instrumentation.ts
> chore(geolocation): allow to control the geolocation feature

- CHANGELOG.md
- packages/core/src/metas/types.ts
- packages/web-sdk/src/index.ts
- packages/web-tracing/src/faroMetaAttributesSpanProcessor.test.ts
- packages/web-tracing/src/faroMetaAttributesSpanProcessor.ts
- packages/web-tracing/src/instrumentation.ts
The web-tracing instrumentation now takes care to add user attributes to spans.
The `UserMeta` was updated with more properties to be aligned with [otel semantic conventions for user](https://opentelemetry.io/docs/specs/semconv/attributes-registry/user/).
* Add missing attributes to user meta to be compatible with otel semantic attributes
* create new span exporter which takes care of adding session and user attributes to spans
> chore(web-tracing): attach user attributes to spans

- CHANGELOG.md
- packages/core/src/config/types.ts
- packages/web-sdk/src/config/makeCoreConfig.test.ts
- packages/web-sdk/src/config/makeCoreConfig.ts
- packages/web-sdk/src/instrumentations/webVitals/instrumentation.ts
- packages/web-sdk/src/instrumentations/webVitals/webVitalsBasic.ts
- packages/web-sdk/src/instrumentations/webVitals/webVitalsWithAttribution.ts
solves #947 
provides the option to enable the `trackAllChanges` feature in the web-vitals package 
add `reportAllWebVitalChanges` to the config object to enable that feature in the web-vitals package
> feat: adding ability to track all changes for web vitals

- CHANGELOG.md
- packages/web-tracing/package.json
- packages/web-tracing/src/instrumentation.ts
- yarn.lock
Remove `ZoneContextManager`  from the web-tracing instrumentation because it's not needed by Faro's default web-tracing instruments.
If users add more instrumentation manually, they now need to inject the context manager via teh web-tracing config.
```ts
initializeFaro({
instrumentations: [
...getWebInstrumentations({
captureConsole: true,
}),
new TracingInstrumentation({
contextManager: new ZoneContextManager(),
}),
],
});
```
This removes `36.3 kB (minified)`  | `12.2 kB (minified + gzip)` from the bundle
and decreases loading time by `245ms (slow 3g) | 14ms (emerging 4g)`. https://bundlephobia.com/package/@opentelemetry/context-zone@1.30.1
`
* Remove ZoneContextManager
* add spanProcessor via `WebTracerConfig` instead of the deprecated `provider.addSpanProcessor()` function
> chore(web-tracing): remove zone-context-manager

- packages/core/src/api/meta/initilialize.test.ts
- packages/core/src/config/types.ts
- packages/web-sdk/src/config/makeCoreConfig.test.ts
- packages/web-sdk/src/config/makeCoreConfig.ts
Flatten the geolocation config for easy of use.
The feature isn't released so the change hasn't any negative effects on our users.
Change to a simple property instead of config object with a nested `enabled` property
> chore(config): flatten geolocation tracking settings

- docs/sources/tutorials/quick-start-browser.md
rom quick-start-browser docs: Remove instruments fwe do longer include by default 
See above
> fix(quick-start-browser docs): update default otel instruments

- CHANGELOG.md
- packages/core/src/api/events/initialize.test.ts
- packages/core/src/api/events/initialize.ts
- packages/core/src/api/exceptions/initialize.test.ts
- packages/core/src/api/exceptions/initialize.ts
- packages/core/src/api/logs/initialize.test.ts
- packages/core/src/api/logs/initialize.ts
- packages/core/src/api/logs/types.ts
- packages/core/src/api/measurements/initialize.test.ts
- packages/core/src/api/measurements/initialize.ts
- packages/web-sdk/src/instrumentations/errors/getErrorDetails.test.ts
Faro always added an empty object for empty `attribute` and `context` data.
This unnecessarily waists resources.
Ensure to not add the respective properties if no data is available
> chore: don't add empty context or attribute objects if no data is provided

- demo/src/client/faro/initialize.ts
- packages/core/src/config/types.ts
- packages/web-sdk/src/config/makeCoreConfig.test.ts
- packages/web-sdk/src/config/makeCoreConfig.ts
- packages/web-sdk/src/instrumentations/performance/resource.test.ts
- packages/web-sdk/src/instrumentations/performance/resource.ts
- packages/web-sdk/src/instrumentations/userActions/processUserActionEventHandler.test.ts
We put back the option to enable user action support
> chore: add user actions preview option

- CHANGELOG.md
- Improvement (`@grafana/faro-core`): Avoid sending empty `attributes` or `context` objects
when no data is provided (#1089)
> chore: 1.14.2 changelog

- CHANGELOG.md
- demo/src/client/faro/initialize.ts
- packages/core/src/api/const.ts
- packages/core/src/api/events/initialize.test.ts
- packages/core/src/api/events/initialize.ts
- packages/core/src/api/exceptions/initialize.test.ts
- packages/core/src/api/exceptions/initialize.ts
- packages/core/src/api/index.ts
- packages/core/src/api/logs/initialize.test.ts
- packages/core/src/api/logs/initialize.ts
- packages/core/src/api/measurements/initialize.test.ts
- packages/core/src/api/measurements/initialize.ts
- packages/core/src/api/types.ts
- packages/core/src/api/userActionLifecycleHandler.test.ts
- packages/core/src/api/userActionLifecycleHandler.ts
- packages/core/src/index.ts
- packages/core/src/utils/index.ts
- packages/core/src/utils/reactive.test.ts
- packages/core/src/utils/reactive.ts
- packages/web-sdk/src/index.ts
- packages/web-sdk/src/instrumentations/userActions/const.ts
- packages/web-sdk/src/instrumentations/userActions/httpRequestMonitor.test.ts
- packages/web-sdk/src/instrumentations/userActions/httpRequestMonitor.ts
- packages/web-sdk/src/instrumentations/userActions/index.ts
- packages/web-sdk/src/instrumentations/userActions/processUserActionEventHandler.test.ts
- packages/web-sdk/src/instrumentations/userActions/processUserActionEventHandler.ts
- packages/web-sdk/src/instrumentations/userActions/types.ts
- packages/web-tracing/src/faroUserActionSpanProcessor.test.ts
- packages/web-tracing/src/faroUserActionSpanProcessor.ts
Second iteration on the user-actions feature.
It:
- Refactors the observables for ease of use
- Takes long running HTTP requests into account
When a pending HTTP requests is detected, the instrumentation sends a 'halt' event/
Once in halt state:
- no additional signals are attached to the action
- A timeout to wait for pending requests starts.
-  If the timeout is reached, faro ends the user-action and sends the event and it's child events
> chore: User action update durations

- CHANGELOG.md
Prepare release 1.15.0.
Main reason for a the minor version increase is the fact that we moved to TS5.
It also contains the alpha/preview version of the user actions feature.
It's not meant to use in production and subject to frequent changes.
> chore(release): prepare 1.15.0

- CHANGELOG.md
- demo/src/client/pages/Features/TracingInstrumentation.tsx
- packages/web-sdk/src/index.ts
- packages/web-sdk/src/instrumentations/index.ts
- packages/web-sdk/src/instrumentations/userActions/index.ts
- packages/web-sdk/src/instrumentations/userActions/instrumentation.test.ts
- packages/web-sdk/src/instrumentations/userActions/instrumentation.ts
- packages/web-sdk/src/instrumentations/userActions/processUserActionEventHandler.test.ts
- packages/web-sdk/src/instrumentations/userActions/processUserActionEventHandler.ts
- packages/web-sdk/src/instrumentations/userActions/types.ts
Provide a function to start user actions.
Sometimes it isn't possible to add `data-` attributes to elements to trigger an action.
Another use case it to add custom attributes to a user-action event which can be doen via the function
I decided against a dedicated API yet bc I am not sure if this really belongs there. But I am open for discussion.
> chore(User actions): provide function to start an action

- CHANGELOG.md
- experimental/CHANGELOG.md
- Improvement (`@grafana/faro-web-sdk`): Provide a function to start a user-action (#1115).
- Dependencies (`@grafana/faro-*`): Upgrade OpenTelemetry dependencies to v0.200.\* (#1126).
> chore(release): 1.16.0

- CHANGELOG.md
- demo/src/client/faro/initialize.ts
- packages/core/src/api/exceptions/index.ts
- packages/core/src/api/exceptions/initialize.test.ts
- packages/core/src/api/exceptions/initialize.ts
- packages/core/src/api/exceptions/types.ts
- packages/core/src/api/index.ts
- packages/core/src/config/types.ts
- packages/core/src/index.ts
- packages/core/src/transports/initialize.ts
- packages/core/src/transports/transports.test.ts
- packages/web-sdk/src/config/makeCoreConfig.ts
- packages/web-sdk/src/index.ts
Provide an option to instruct Faro to provide the original error in a Faro error payload.
This is useful to handle special cases in uncontrolled environments/libraries or other enhanced use cases.
I allows to enrich the Faro error before sending it to the collector.
Examples:
* `throw undefined`
* `throw ''`
* Enriching errors while they bubble up to a global error handler which rethrows itself. 
*...
To not unnecessary increase resource user for users who don't use the feature, the option needs to enabled via the `preserveOriginalError: true` property.
If enabled, Faro adds a `orginalError` property to the Faro exception payload holding a ref to the original JS Error.
The `orginalError` is not handled by the Faro receiver so it is removed before sending the data to not unnecessarily …
> chore(error tracking): provide original error to beforeSend hook

- CHANGELOG.md
- packages/react/src/index.ts
The ExceptionEventExtended event wasn't exported by the faro-react package.
USer could import it form the web-sdk package but it's confusing if all other imports are provded by the faro-react package
> fix(faro-react): re-export the ExceptionEventExtended type

- CHANGELOG.md
- packages/web-sdk/src/index.ts
- packages/web-tracing/src/faroTraceExporter.utils.test.ts
- packages/web-tracing/src/faroTraceExporter.utils.ts
- packages/web-tracing/src/faroUserActionSpanProcessor.test.ts
- packages/web-tracing/src/faroUserActionSpanProcessor.ts
- packages/web-tracing/src/types.ts
On HTTP request Faro sned to items: a `trace` and a Faro sidecar event (`faro.tracing.fecth|xhr`). For cloud users the Faro is shown in the user-journey table.
The Faro event wasn't send for the CDN bundle.
The issue was that the imported `faro` object was `undefined` so `faro.api.pushEvent()` couldn't be executed.
The reason why it was undefined was because some items where imported from the `faro-core` package which isn't flagged a dependency for the `web-tracing` package.
While this is no issue with the other bundles, it is for the `IIFE` (cdn) bundle.
We do only add the web-sdk package as an explicit dependency to IIFE bundle because it already contains the faro-core code. 
The solution was to import the re-exported items from the web-sdk package instead of the faro-core package
* …
> fix(web-tracing): no Faro events for HTTP requests in CDN bundle

- packages/web-sdk/src/instrumentations/performance/performanceUtils.test.ts
- packages/web-sdk/src/instrumentations/performance/performanceUtils.ts
Reset negative values to `0` when calculating  
`FaroResourceTiming`s
* Update `toFaroPerformanceTimingString()`
> chore(resource-timings): guard against negative values

- CHANGELOG.md
- packages/web-sdk/src/instrumentations/performance/performanceUtils.test.ts
- packages/web-sdk/src/instrumentations/performance/performanceUtils.ts
- packages/web-sdk/src/instrumentations/performance/performanceUtilsTestData.ts
Fixed a bug in the calculation of teh TLS negotiation time.
`tslNegotiationTime = connectEnd - secureConnectionStart;`
> fix(resource timings): tlsNegotiationTime was wrong

- CHANGELOG.md
- packages/core/src/api/exceptions/initialize.test.ts
- packages/core/src/api/exceptions/initialize.ts
- packages/core/src/api/exceptions/types.ts
- packages/core/src/transports/transports.test.ts
- packages/web-sdk/src/instrumentations/errors/registerOnerror.test.ts
- packages/web-sdk/src/instrumentations/errors/registerOnerror.ts
Ignoring errors didn't work properly when matching stack only strings.
This was because the parsed error was used which contains parsed stack frames and not the original stack string anymore. 
Open up the options object of the `pushError` API to inject the original error as well.
The original error is then used to check if the error has a match in the `ignoreErrors` list.
Additionally we no (correctly) assign original error to the  `originalError` object in the exception signal payload.
This is used if [preserveOriginalError](https://grafana.com/docs/grafana-cloud/monitor-applications/frontend-observability/instrument/error-tracking/#handle-other-edge-cases) is enabled.
Fixes: #1160
> fix(ignoreErrors): ensure to match on the original error and not on the parsed error

- CHANGELOG.md
- packages/web-sdk/src/instrumentations/performance/performanceUtils.test.ts
- packages/web-sdk/src/instrumentations/performance/performanceUtils.ts
- packages/web-sdk/src/instrumentations/performance/types.ts
In Faro we only tracked the body size which doesn't reflects the whole size of a request.
Transfer size shows thee size of the whole request including more data as the body only. Also, if a resource resource is loaded from cache it shows size `0` which refelcts the truth.
If e. gs a user wants to track the wheight of requests, transferSize would reflect teh real number while body size wouldn't becasue it also has a value > 0 when loaded from cache. 
* Add transferSize to performance timings
* [Docs PR](https://github.com/grafana/website/pull/25499)
> chore(PerformanceInstrumentation): track transfer size

- .github/workflows/pull-request.yml
- .nvmrc
- CHANGELOG.md
- demo/package.json
- experimental/instrumentation-fetch/package.json
- experimental/instrumentation-performance-timeline/package.json
- experimental/instrumentation-xhr/package.json
- experimental/transport-otlp-http/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
- packages/web-sdk/package.json
- packages/web-tracing/package.json
Faro supports only maintained Node versions.
[Node 18 went EoL on Mar 27, 2025](https://nodejs.org/en/about/previous-releases#looking-for-the-latest-release-of-a-version-branch)
> chore(deps): update Node version support to satisfy EoL of Node18

- .github/workflows/pull-request.yml
- .nvmrc
- CHANGELOG.md
- demo/package.json
- experimental/instrumentation-fetch/package.json
- experimental/instrumentation-performance-timeline/package.json
- experimental/instrumentation-xhr/package.json
- experimental/transport-otlp-http/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
- packages/web-sdk/package.json
- packages/web-tracing/package.json
- yarn.lock
seems that semver conventions dictates that this should be a major release - so I will deprecate 1.18.0 and release a hotfix as 1.18.1
> chore: reverting node 18 change and preparing 1.18.1 release

- packages/web-tracing/src/instrumentation.ts
- packages/web-tracing/src/semconv.ts
Add resource attributes for runtime and distro yo make it more staright forward to query respective spans.
Add above attr. 
Note:
They are not stable and the OTEL suggested way is to create own files to hold the attributes to prevent breakage.
> chore(web-tracing): add resource attrs. for browser and distribution

- .github/workflows/pull-request.yml
- README.md
- demo/package.json
- experimental/instrumentation-fetch/package.json
- experimental/instrumentation-performance-timeline/package.json
- experimental/instrumentation-xhr/package.json
- experimental/transport-otlp-http/package.json
- package.json
- packages/core/package.json
- packages/react/package.json
- packages/web-sdk/package.json
- packages/web-tracing/package.json
Remove the node engine object and update the supported node versions in the test matrix. 
See above
> chore(deps): remove node 18 support, add node 24 support

- packages/web-sdk/src/index.ts
- packages/web-sdk/src/instrumentations/userActions/processUserActionEventHandler.ts
- packages/web-tracing/src/faroUserActionSpanProcessor.test.ts
- packages/web-tracing/src/faroUserActionSpanProcessor.ts
When a action has long pending http requests it starts an extended timer if the regular action timeout is reached while waiting for the pending requests to resolve and the action goes in `halt` state .
The `halt` state indicates that the regular action has been finished bc no further eligible event happened within the respective timeframes and it waits for the pending requests to finish.
This can already happen on slow connection (can be tested with throttling in the browser).
Because we forgot to respect the `halt` state in the web tracing package it could happen that any requests sent during the `halt` phase (remember they don't belong to the action anymore) were still mapped to the action.
Note:
As long as the action is in `halt` state no new action can be started. 
* add the missing …
> chore(user actions): don't attach user action context to http request when in halt mode

- CHANGELOG.md
- packages/core/src/instrumentations/initialize.ts
- packages/web-sdk/src/config/getWebInstrumentations.ts
- packages/web-sdk/src/config/types.ts
- packages/web-sdk/src/index.ts
- packages/web-sdk/src/instrumentations/csp/index.ts
- packages/web-sdk/src/instrumentations/csp/instrumentation.test.ts
- packages/web-sdk/src/instrumentations/csp/instrumentation.ts
- packages/web-sdk/src/instrumentations/index.ts
In order to support Content Security Policy violation payloads
Create a new CSPInstrumenetation that registers to the `securitypolicyviolation` event and forwards the payload as a Faro event. Although this is not pedantic in terms of using the `Report-To` header etc, it is a way of getting this event into the pipeline and utilising all the metadata Faro SDK provides.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CSP
> feat(web-sdk): add Content Security Policy Instrumentation

- CHANGELOG.md
- Feature (`@grafana/faro-web-sdk`): Add CSP instrumentation (#1312)
- Improvement (`@grafana/faro-*`): Rename `userActionEventType` to `userActionTrigger` for improved clarity (#1298)
- Chore (`@grafana/faro-web-sdk`): Prevent tracking of custom collector URLs that don't match the Faro collector
URL structure (#1297)
- Chore (`@grafana/faro-core`): Ensure first instrumentation gets properly removed (#1312)
- Chore (`@grafana/faro-*`): Remove Node.js 23 from build and test matrix as it's EoL (#1343)
- Chore (`@grafana/faro-*`): upgrade to yarn 4
> chore(release): 1.19.0 changelog

- CHANGELOG.md
- packages/web-sdk/src/instrumentations/errors/stackFrames/const.ts
- packages/web-sdk/src/instrumentations/errors/stackFrames/getStackFramesFromError.test.ts
`filename` is not being extracted properly when no function name or method is provided on chrome, and the URL includes parentheses, causing the filename to be wrongly resolved, as shown in this test snapshot
```
{
"colno": 27,
-     "filename": "http://localhost:8080/[brackets]/(paranthesis)/file.js",
-     "func": undefined,
+     "filename": "paranthesis)/file.js",
+     "func": "http://localhost:8080/[brackets]/",
"lineno": 41,
}, 
```
To fix this, the `webkitLineRegex` was changed to have a negative lookahead for function name capture group preventing it from matching URLs
> fix: prevent filename from being badly extracted when no function name is resolved

- .github/workflows/pull-request.yml
- .github/workflows/release.yml
Zizmor failed because soem images weren't pinned.
```
error[unpinned-images]: unpinned image references
--> ./.github/workflows/pull-request.yml:52:7
|
52 |       image: cypress/browsers
|       ^^^^^^^^^^^^^^^^^^^^^^^ container image is unpinned
|
= note: audit confidence → High
error[unpinned-images]: unpinned image references
--> ./.github/workflows/pull-request.yml:57:9
|
57 |         image: postgres:latest
|         ^^^^^^^^^^^^^^^^^^^^^^ container image is pinned to latest
|
= note: audit confidence → High
error[unpinned-images]: unpinned image references
--> ./.github/workflows/release.yml:54:9
|
54 |         image: postgres:latest
|         ^^^^^^^^^^^^^^^^^^^^^^ container image is pinned to latest
|
= note: audit confidence → High
14 findings (11 suppressed): 0 unknown, 0 …
```
> chore(actions): pin images

- README.md
The latest beta version is `2.0.0-beta-2`. The README has instructions to specifically install `2.0.0-beta`.
This changes the single version to a range, so that the latest beta version is installed.
> chore: updated readme with beta version range

- experimental/transport-otlp-http/README.md
The npm published name and the name in readme do not currently match, which is confusing in npm.
Updated the name :)
> chore(readme): updated transport-otlp-http package name in readme to match npm name

- CHANGELOG.md
- cypress/e2e/demo/events.cy.ts
- demo/src/client/pages/Features/TracingInstrumentation.tsx
- packages/core/src/api/userActions/initialize.test.ts
- packages/core/src/api/userActions/initialize.ts
- packages/react/src/index.ts
- packages/web-sdk/src/index.ts
Custom triggers and severity weren't were missing in user action attributes.
* Ensure trigger and severity are added
* Export `UserActionSeverity` from web-sdk and faro-react so users can import and use it more easy
_Action attributes contain the default values for trigger and severity_
_Action attributes contain the custom values for trigger and severity_
> fix(user-actions): custom severity wasn't added to user action attributes

- .github/dependabot.yaml
Do not include npm package releases younger than 3 days to help avoid pulling in compromised packages.
* [Slack discussion (internal)](https://raintank-corp.slack.com/archives/C05N7699TQ9/p1757668273319979)
> chore(dependabot): add  3 days cooldown
